#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ISE.SM.Model;

namespace ISE.SM.Model	
{
	public partial class EntitiesModel1 : OpenAccessContext, IEntitiesModel1UnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel1.rlinq");
		
		public EntitiesModel1()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel1(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel1(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel1(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel1(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<User> Users 
		{
			get
			{
				return this.GetAll<User>();
			}
		}
		
		public IQueryable<UserToRoleConstraint> UserToRoleConstraints 
		{
			get
			{
				return this.GetAll<UserToRoleConstraint>();
			}
		}
		
		public IQueryable<UserToRole> UserToRoles 
		{
			get
			{
				return this.GetAll<UserToRole>();
			}
		}
		
		public IQueryable<UserToGroup> UserToGroups 
		{
			get
			{
				return this.GetAll<UserToGroup>();
			}
		}
		
		public IQueryable<UserToCompany> UserToCompanies 
		{
			get
			{
				return this.GetAll<UserToCompany>();
			}
		}
		
		public IQueryable<UserResourceScope> UserResourceScopes 
		{
			get
			{
				return this.GetAll<UserResourceScope>();
			}
		}
		
		public IQueryable<UserProfile> UserProfiles 
		{
			get
			{
				return this.GetAll<UserProfile>();
			}
		}
		
		public IQueryable<UserLog> UserLogs 
		{
			get
			{
				return this.GetAll<UserLog>();
			}
		}
		
		public IQueryable<SoftwareDomain> SoftwareDomains 
		{
			get
			{
				return this.GetAll<SoftwareDomain>();
			}
		}
		
		public IQueryable<SecurityUserLog> SecurityUserLogs 
		{
			get
			{
				return this.GetAll<SecurityUserLog>();
			}
		}
		
		public IQueryable<SecuritySession> SecuritySessions 
		{
			get
			{
				return this.GetAll<SecuritySession>();
			}
		}
		
		public IQueryable<SecurityResource> SecurityResources 
		{
			get
			{
				return this.GetAll<SecurityResource>();
			}
		}
		
		public IQueryable<SecurityGroup> SecurityGroups 
		{
			get
			{
				return this.GetAll<SecurityGroup>();
			}
		}
		
		public IQueryable<Scope> Scopes 
		{
			get
			{
				return this.GetAll<Scope>();
			}
		}
		
		public IQueryable<RoleToRoleConstraint> RoleToRoleConstraints 
		{
			get
			{
				return this.GetAll<RoleToRoleConstraint>();
			}
		}
		
		public IQueryable<RoleToRole> RoleToRoles 
		{
			get
			{
				return this.GetAll<RoleToRole>();
			}
		}
		
		public IQueryable<RoleToGroup> RoleToGroups 
		{
			get
			{
				return this.GetAll<RoleToGroup>();
			}
		}
		
		public IQueryable<Role> Roles 
		{
			get
			{
				return this.GetAll<Role>();
			}
		}
		
		public IQueryable<ResourceType> ResourceTypes 
		{
			get
			{
				return this.GetAll<ResourceType>();
			}
		}
		
		public IQueryable<ResourceToOperation> ResourceToOperations 
		{
			get
			{
				return this.GetAll<ResourceToOperation>();
			}
		}
		
		public IQueryable<PermissionToUser> PermissionToUsers 
		{
			get
			{
				return this.GetAll<PermissionToUser>();
			}
		}
		
		public IQueryable<PermissionToRole> PermissionToRoles 
		{
			get
			{
				return this.GetAll<PermissionToRole>();
			}
		}
		
		public IQueryable<Permission> Permissions 
		{
			get
			{
				return this.GetAll<Permission>();
			}
		}
		
		public IQueryable<PasswordHistory> PasswordHistories 
		{
			get
			{
				return this.GetAll<PasswordHistory>();
			}
		}
		
		public IQueryable<OperationConstraint> OperationConstraints 
		{
			get
			{
				return this.GetAll<OperationConstraint>();
			}
		}
		
		public IQueryable<Operation> Operations 
		{
			get
			{
				return this.GetAll<Operation>();
			}
		}
		
		public IQueryable<ManagementRole> ManagementRoles 
		{
			get
			{
				return this.GetAll<ManagementRole>();
			}
		}
		
		public IQueryable<ManagementLog> ManagementLogs 
		{
			get
			{
				return this.GetAll<ManagementLog>();
			}
		}
		
		public IQueryable<ManagementAccount> ManagementAccounts 
		{
			get
			{
				return this.GetAll<ManagementAccount>();
			}
		}
		
		public IQueryable<LoginType> LoginTypes 
		{
			get
			{
				return this.GetAll<LoginType>();
			}
		}
		
		public IQueryable<GroupToGroup> GroupToGroups 
		{
			get
			{
				return this.GetAll<GroupToGroup>();
			}
		}
		
		public IQueryable<Company> Companies 
		{
			get
			{
				return this.GetAll<Company>();
			}
		}
		
		public IQueryable<ApplicationDomain> ApplicationDomains 
		{
			get
			{
				return this.GetAll<ApplicationDomain>();
			}
		}
		
		public IQueryable<AccountToAppDomain> AccountToAppDomains 
		{
			get
			{
				return this.GetAll<AccountToAppDomain>();
			}
		}
		
		public IQueryable<Account> Accounts 
		{
			get
			{
				return this.GetAll<Account>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "Oracle";
			backend.ProviderName = "Oracle.DataAccess.Client";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel1.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel1.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModel1UnitOfWork : IUnitOfWork
	{
		IQueryable<User> Users
		{
			get;
		}
		IQueryable<UserToRoleConstraint> UserToRoleConstraints
		{
			get;
		}
		IQueryable<UserToRole> UserToRoles
		{
			get;
		}
		IQueryable<UserToGroup> UserToGroups
		{
			get;
		}
		IQueryable<UserToCompany> UserToCompanies
		{
			get;
		}
		IQueryable<UserResourceScope> UserResourceScopes
		{
			get;
		}
		IQueryable<UserProfile> UserProfiles
		{
			get;
		}
		IQueryable<UserLog> UserLogs
		{
			get;
		}
		IQueryable<SoftwareDomain> SoftwareDomains
		{
			get;
		}
		IQueryable<SecurityUserLog> SecurityUserLogs
		{
			get;
		}
		IQueryable<SecuritySession> SecuritySessions
		{
			get;
		}
		IQueryable<SecurityResource> SecurityResources
		{
			get;
		}
		IQueryable<SecurityGroup> SecurityGroups
		{
			get;
		}
		IQueryable<Scope> Scopes
		{
			get;
		}
		IQueryable<RoleToRoleConstraint> RoleToRoleConstraints
		{
			get;
		}
		IQueryable<RoleToRole> RoleToRoles
		{
			get;
		}
		IQueryable<RoleToGroup> RoleToGroups
		{
			get;
		}
		IQueryable<Role> Roles
		{
			get;
		}
		IQueryable<ResourceType> ResourceTypes
		{
			get;
		}
		IQueryable<ResourceToOperation> ResourceToOperations
		{
			get;
		}
		IQueryable<PermissionToUser> PermissionToUsers
		{
			get;
		}
		IQueryable<PermissionToRole> PermissionToRoles
		{
			get;
		}
		IQueryable<Permission> Permissions
		{
			get;
		}
		IQueryable<PasswordHistory> PasswordHistories
		{
			get;
		}
		IQueryable<OperationConstraint> OperationConstraints
		{
			get;
		}
		IQueryable<Operation> Operations
		{
			get;
		}
		IQueryable<ManagementRole> ManagementRoles
		{
			get;
		}
		IQueryable<ManagementLog> ManagementLogs
		{
			get;
		}
		IQueryable<ManagementAccount> ManagementAccounts
		{
			get;
		}
		IQueryable<LoginType> LoginTypes
		{
			get;
		}
		IQueryable<GroupToGroup> GroupToGroups
		{
			get;
		}
		IQueryable<Company> Companies
		{
			get;
		}
		IQueryable<ApplicationDomain> ApplicationDomains
		{
			get;
		}
		IQueryable<AccountToAppDomain> AccountToAppDomains
		{
			get;
		}
		IQueryable<Account> Accounts
		{
			get;
		}
	}
}
namespace ISE.SM.Model	
{
	public partial class User
	{
		private int? _updateuserid;
		public virtual int? UpdateUserId
		{
			get
			{
				return this._updateuserid;
			}
			set
			{
				this._updateuserid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _personelcode;
		public virtual string PersonelCode
		{
			get
			{
				return this._personelcode;
			}
			set
			{
				this._personelcode = value;
			}
		}
		
		private int? _perid;
		public virtual int? PerId
		{
			get
			{
				return this._perid;
			}
			set
			{
				this._perid = value;
			}
		}
		
		private string _nationalno;
		public virtual string NationalNo
		{
			get
			{
				return this._nationalno;
			}
			set
			{
				this._nationalno = value;
			}
		}
		
		private string _lastname;
		public virtual string LastName
		{
			get
			{
				return this._lastname;
			}
			set
			{
				this._lastname = value;
			}
		}
		
		private short? _isrealperson;
		public virtual short? IsRealPerson
		{
			get
			{
				return this._isrealperson;
			}
			set
			{
				this._isrealperson = value;
			}
		}
		
		private int? _insertuserid;
		public virtual int? InsertUserId
		{
			get
			{
				return this._insertuserid;
			}
			set
			{
				this._insertuserid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _firstname;
		public virtual string FirstName
		{
			get
			{
				return this._firstname;
			}
			set
			{
				this._firstname = value;
			}
		}
		
		private DateTime? _lockdate;
		public virtual DateTime? LockDate
		{
			get
			{
				return this._lockdate;
			}
			set
			{
				this._lockdate = value;
			}
		}
		
		private int? _companyid;
		public virtual int? CompanyId
		{
			get
			{
				return this._companyid;
			}
			set
			{
				this._companyid = value;
			}
		}
		
		private int _userid;
		public virtual int UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private IList<Account> _accounts = new List<Account>();
		public virtual IList<Account> Accounts
		{
			get
			{
				return this._accounts;
			}
		}
		
		private IList<UserLog> _userlogs = new List<UserLog>();
		public virtual IList<UserLog> UserLogs
		{
			get
			{
				return this._userlogs;
			}
		}
		
		private IList<UserProfile> _userprofiles = new List<UserProfile>();
		public virtual IList<UserProfile> UserProfiles
		{
			get
			{
				return this._userprofiles;
			}
		}
		
		private IList<UserResourceScope> _userresourcescopes = new List<UserResourceScope>();
		public virtual IList<UserResourceScope> UserResourceScopes
		{
			get
			{
				return this._userresourcescopes;
			}
		}
		
		private IList<UserToCompany> _usertocompanies = new List<UserToCompany>();
		public virtual IList<UserToCompany> UserToCompanies
		{
			get
			{
				return this._usertocompanies;
			}
		}
		
		private IList<UserToGroup> _usertogroups = new List<UserToGroup>();
		public virtual IList<UserToGroup> UserToGroups
		{
			get
			{
				return this._usertogroups;
			}
		}
		
		private IList<UserToRole> _usertoroles = new List<UserToRole>();
		public virtual IList<UserToRole> UserToRoles
		{
			get
			{
				return this._usertoroles;
			}
		}
		
		private IList<UserToRoleConstraint> _usertoroleconstraints = new List<UserToRoleConstraint>();
		public virtual IList<UserToRoleConstraint> UserToRoleConstraints
		{
			get
			{
				return this._usertoroleconstraints;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserToRoleConstraint
	{
		private long _urconstraintid;
		public virtual long UrConstraintId
		{
			get
			{
				return this._urconstraintid;
			}
			set
			{
				this._urconstraintid = value;
			}
		}
		
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private int? _roleid;
		public virtual int? RoleId
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private short? _enable;
		public virtual short? Enable
		{
			get
			{
				return this._enable;
			}
			set
			{
				this._enable = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserToRole
	{
		private long _urid;
		public virtual long UrId
		{
			get
			{
				return this._urid;
			}
			set
			{
				this._urid = value;
			}
		}
		
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private int? _roleid;
		public virtual int? RoleId
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserToGroup
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int _ugid;
		public virtual int UgId
		{
			get
			{
				return this._ugid;
			}
			set
			{
				this._ugid = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private int? _groupid;
		public virtual int? GroupId
		{
			get
			{
				return this._groupid;
			}
			set
			{
				this._groupid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private SecurityGroup _securitygroup;
		public virtual SecurityGroup Securitygroup
		{
			get
			{
				return this._securitygroup;
			}
			set
			{
				this._securitygroup = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserToCompany
	{
		private long _usertocompanyid;
		public virtual long UserToCompanyId
		{
			get
			{
				return this._usertocompanyid;
			}
			set
			{
				this._usertocompanyid = value;
			}
		}
		
		private DateTime? _todate;
		public virtual DateTime? ToDate
		{
			get
			{
				return this._todate;
			}
			set
			{
				this._todate = value;
			}
		}
		
		private long? _securityuserid;
		public virtual long? SecurityUserId
		{
			get
			{
				return this._securityuserid;
			}
			set
			{
				this._securityuserid = value;
			}
		}
		
		private int? _companyid;
		public virtual int? CompanyId
		{
			get
			{
				return this._companyid;
			}
			set
			{
				this._companyid = value;
			}
		}
		
		private DateTime? _fromdate;
		public virtual DateTime? FromDate
		{
			get
			{
				return this._fromdate;
			}
			set
			{
				this._fromdate = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserResourceScope
	{
		private long _userresourcescopeid;
		public virtual long UserResourceScopeId
		{
			get
			{
				return this._userresourcescopeid;
			}
			set
			{
				this._userresourcescopeid = value;
			}
		}
		
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private long? _resourceid;
		public virtual long? ResourceId
		{
			get
			{
				return this._resourceid;
			}
			set
			{
				this._resourceid = value;
			}
		}
		
		private int? _scopeid;
		public virtual int? ScopeId
		{
			get
			{
				return this._scopeid;
			}
			set
			{
				this._scopeid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private SecurityResource _securityresource;
		public virtual SecurityResource Securityresource
		{
			get
			{
				return this._securityresource;
			}
			set
			{
				this._securityresource = value;
			}
		}
		
		private Scope _scope;
		public virtual Scope Scope
		{
			get
			{
				return this._scope;
			}
			set
			{
				this._scope = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserProfile
	{
		private long _userprofileid;
		public virtual long UserProfileId
		{
			get
			{
				return this._userprofileid;
			}
			set
			{
				this._userprofileid = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class UserLog
	{
		private long _userlogid;
		public virtual long UserLogId
		{
			get
			{
				return this._userlogid;
			}
			set
			{
				this._userlogid = value;
			}
		}
		
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private long? _resourceid;
		public virtual long? ResourceId
		{
			get
			{
				return this._resourceid;
			}
			set
			{
				this._resourceid = value;
			}
		}
		
		private short? _runtype;
		public virtual short? RunType
		{
			get
			{
				return this._runtype;
			}
			set
			{
				this._runtype = value;
			}
		}
		
		private long? _operationid;
		public virtual long? OperationId
		{
			get
			{
				return this._operationid;
			}
			set
			{
				this._operationid = value;
			}
		}
		
		private DateTime? _logdatetime;
		public virtual DateTime? LogDateTime
		{
			get
			{
				return this._logdatetime;
			}
			set
			{
				this._logdatetime = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _computername;
		public virtual string ComputerName
		{
			get
			{
				return this._computername;
			}
			set
			{
				this._computername = value;
			}
		}
		
		private SecurityResource _securityresource;
		public virtual SecurityResource Securityresource
		{
			get
			{
				return this._securityresource;
			}
			set
			{
				this._securityresource = value;
			}
		}
		
		private Operation _operation;
		public virtual Operation Operation
		{
			get
			{
				return this._operation;
			}
			set
			{
				this._operation = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class SoftwareDomain
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int _softwaredomainid;
		public virtual int SoftwareDomainId
		{
			get
			{
				return this._softwaredomainid;
			}
			set
			{
				this._softwaredomainid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private int? _precedency;
		public virtual int? Precedency
		{
			get
			{
				return this._precedency;
			}
			set
			{
				this._precedency = value;
			}
		}
		
		private IList<SecurityResource> _securityresources = new List<SecurityResource>();
		public virtual IList<SecurityResource> SecurityResources
		{
			get
			{
				return this._securityresources;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class SecurityUserLog
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _service;
		public virtual string Service
		{
			get
			{
				return this._service;
			}
			set
			{
				this._service = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private string _sessionid;
		public virtual string SessionId
		{
			get
			{
				return this._sessionid;
			}
			set
			{
				this._sessionid = value;
			}
		}
		
		private long _securityuserlogid;
		public virtual long SecurityUserLogId
		{
			get
			{
				return this._securityuserlogid;
			}
			set
			{
				this._securityuserlogid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private int? _appdomainid;
		public virtual int? AppDomainId
		{
			get
			{
				return this._appdomainid;
			}
			set
			{
				this._appdomainid = value;
			}
		}
		
		private string _actionparam;
		public virtual string ActionParam
		{
			get
			{
				return this._actionparam;
			}
			set
			{
				this._actionparam = value;
			}
		}
		
		private string _action;
		public virtual string Action
		{
			get
			{
				return this._action;
			}
			set
			{
				this._action = value;
			}
		}
		
		private long? _accountid;
		public virtual long? AccountId
		{
			get
			{
				return this._accountid;
			}
			set
			{
				this._accountid = value;
			}
		}
		
		private Account _account;
		public virtual Account Account
		{
			get
			{
				return this._account;
			}
			set
			{
				this._account = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class SecuritySession
	{
		private string _securitysessionid;
		public virtual string SecuritySessionId
		{
			get
			{
				return this._securitysessionid;
			}
			set
			{
				this._securitysessionid = value;
			}
		}
		
		private DateTime? _expireddate;
		public virtual DateTime? ExpiredDate
		{
			get
			{
				return this._expireddate;
			}
			set
			{
				this._expireddate = value;
			}
		}
		
		private DateTime? _createdate;
		public virtual DateTime? CreateDate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				this._createdate = value;
			}
		}
		
		private int? _appdomainid;
		public virtual int? AppDomainId
		{
			get
			{
				return this._appdomainid;
			}
			set
			{
				this._appdomainid = value;
			}
		}
		
		private long? _accountid;
		public virtual long? AccountId
		{
			get
			{
				return this._accountid;
			}
			set
			{
				this._accountid = value;
			}
		}
		
		private long _rowid;
		public virtual long RowId
		{
			get
			{
				return this._rowid;
			}
			set
			{
				this._rowid = value;
			}
		}
		
		private Account _account;
		public virtual Account Account
		{
			get
			{
				return this._account;
			}
			set
			{
				this._account = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class SecurityResource
	{
		private string _userdescription;
		public virtual string UserDescription
		{
			get
			{
				return this._userdescription;
			}
			set
			{
				this._userdescription = value;
			}
		}
		
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _tooltip;
		public virtual string ToolTip
		{
			get
			{
				return this._tooltip;
			}
			set
			{
				this._tooltip = value;
			}
		}
		
		private string _systempassword;
		public virtual string SystemPassword
		{
			get
			{
				return this._systempassword;
			}
			set
			{
				this._systempassword = value;
			}
		}
		
		private int? _softwaredomainid;
		public virtual int? SoftwareDomainId
		{
			get
			{
				return this._softwaredomainid;
			}
			set
			{
				this._softwaredomainid = value;
			}
		}
		
		private long _securityresourceid;
		public virtual long SecurityResourceId
		{
			get
			{
				return this._securityresourceid;
			}
			set
			{
				this._securityresourceid = value;
			}
		}
		
		private int? _resourcetypeid;
		public virtual int? ResourceTypeId
		{
			get
			{
				return this._resourcetypeid;
			}
			set
			{
				this._resourcetypeid = value;
			}
		}
		
		private string _resourcename;
		public virtual string ResourceName
		{
			get
			{
				return this._resourcename;
			}
			set
			{
				this._resourcename = value;
			}
		}
		
		private int? _precedence;
		public virtual int? Precedence
		{
			get
			{
				return this._precedence;
			}
			set
			{
				this._precedence = value;
			}
		}
		
		private string _path;
		public virtual string Path
		{
			get
			{
				return this._path;
			}
			set
			{
				this._path = value;
			}
		}
		
		private long? _parentid;
		public virtual long? ParentId
		{
			get
			{
				return this._parentid;
			}
			set
			{
				this._parentid = value;
			}
		}
		
		private string _namespace;
		public virtual string Namespace
		{
			get
			{
				return this._namespace;
			}
			set
			{
				this._namespace = value;
			}
		}
		
		private string _loginname;
		public virtual string LoginName
		{
			get
			{
				return this._loginname;
			}
			set
			{
				this._loginname = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _icon;
		public virtual string Icon
		{
			get
			{
				return this._icon;
			}
			set
			{
				this._icon = value;
			}
		}
		
		private short? _hasparameter;
		public virtual short? HasParameter
		{
			get
			{
				return this._hasparameter;
			}
			set
			{
				this._hasparameter = value;
			}
		}
		
		private short? _hasitemaction;
		public virtual short? HasItemAction
		{
			get
			{
				return this._hasitemaction;
			}
			set
			{
				this._hasitemaction = value;
			}
		}
		
		private string _executablefile;
		public virtual string ExecutableFile
		{
			get
			{
				return this._executablefile;
			}
			set
			{
				this._executablefile = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private string _displayname;
		public virtual string DisplayName
		{
			get
			{
				return this._displayname;
			}
			set
			{
				this._displayname = value;
			}
		}
		
		private string _devdescription;
		public virtual string DevDescription
		{
			get
			{
				return this._devdescription;
			}
			set
			{
				this._devdescription = value;
			}
		}
		
		private string _call3;
		public virtual string Call3
		{
			get
			{
				return this._call3;
			}
			set
			{
				this._call3 = value;
			}
		}
		
		private string _call2;
		public virtual string Call2
		{
			get
			{
				return this._call2;
			}
			set
			{
				this._call2 = value;
			}
		}
		
		private string _call1;
		public virtual string Call1
		{
			get
			{
				return this._call1;
			}
			set
			{
				this._call1 = value;
			}
		}
		
		private string _assemblyname;
		public virtual string AssemblyName
		{
			get
			{
				return this._assemblyname;
			}
			set
			{
				this._assemblyname = value;
			}
		}
		
		private int? _appdomainid;
		public virtual int? AppDomainId
		{
			get
			{
				return this._appdomainid;
			}
			set
			{
				this._appdomainid = value;
			}
		}
		
		private ApplicationDomain _applicationdomain;
		public virtual ApplicationDomain Applicationdomain
		{
			get
			{
				return this._applicationdomain;
			}
			set
			{
				this._applicationdomain = value;
			}
		}
		
		private SoftwareDomain _softwaredomain;
		public virtual SoftwareDomain Softwaredomain
		{
			get
			{
				return this._softwaredomain;
			}
			set
			{
				this._softwaredomain = value;
			}
		}
		
		private ResourceType _resourcetype;
		public virtual ResourceType Resourcetype
		{
			get
			{
				return this._resourcetype;
			}
			set
			{
				this._resourcetype = value;
			}
		}
		
		private IList<UserResourceScope> _userresourcescopes = new List<UserResourceScope>();
		public virtual IList<UserResourceScope> UserResourceScopes
		{
			get
			{
				return this._userresourcescopes;
			}
		}
		
		private IList<UserLog> _userlogs = new List<UserLog>();
		public virtual IList<UserLog> UserLogs
		{
			get
			{
				return this._userlogs;
			}
		}
		
		private IList<ResourceToOperation> _resourcetooperations = new List<ResourceToOperation>();
		public virtual IList<ResourceToOperation> ResourceToOperations
		{
			get
			{
				return this._resourcetooperations;
			}
		}
		
		private IList<Permission> _permissions = new List<Permission>();
		public virtual IList<Permission> Permissions
		{
			get
			{
				return this._permissions;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class SecurityGroup
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int _securitygroupid;
		public virtual int SecurityGroupId
		{
			get
			{
				return this._securitygroupid;
			}
			set
			{
				this._securitygroupid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _groupname;
		public virtual string GroupName
		{
			get
			{
				return this._groupname;
			}
			set
			{
				this._groupname = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private string _displayname;
		public virtual string DisplayName
		{
			get
			{
				return this._displayname;
			}
			set
			{
				this._displayname = value;
			}
		}
		
		private int? _appdomainid;
		public virtual int? AppDomainId
		{
			get
			{
				return this._appdomainid;
			}
			set
			{
				this._appdomainid = value;
			}
		}
		
		private IList<UserToGroup> _usertogroups = new List<UserToGroup>();
		public virtual IList<UserToGroup> UserToGroups
		{
			get
			{
				return this._usertogroups;
			}
		}
		
		private IList<RoleToGroup> _roletogroups = new List<RoleToGroup>();
		public virtual IList<RoleToGroup> RoleToGroups
		{
			get
			{
				return this._roletogroups;
			}
		}
		
		private IList<GroupToGroup> _grouptogroups = new List<GroupToGroup>();
		public virtual IList<GroupToGroup> GroupToGroups
		{
			get
			{
				return this._grouptogroups;
			}
		}
		
		private IList<GroupToGroup> _grouptogroups1 = new List<GroupToGroup>();
		public virtual IList<GroupToGroup> GroupToGroups1
		{
			get
			{
				return this._grouptogroups1;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class Scope
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _scopename;
		public virtual string ScopeName
		{
			get
			{
				return this._scopename;
			}
			set
			{
				this._scopename = value;
			}
		}
		
		private int _scopeid;
		public virtual int ScopeId
		{
			get
			{
				return this._scopeid;
			}
			set
			{
				this._scopeid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _displayname;
		public virtual string DisplayName
		{
			get
			{
				return this._displayname;
			}
			set
			{
				this._displayname = value;
			}
		}
		
		private IList<UserResourceScope> _userresourcescopes = new List<UserResourceScope>();
		public virtual IList<UserResourceScope> UserResourceScopes
		{
			get
			{
				return this._userresourcescopes;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class RoleToRoleConstraint
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int _rrconstraintid;
		public virtual int RrConstraintId
		{
			get
			{
				return this._rrconstraintid;
			}
			set
			{
				this._rrconstraintid = value;
			}
		}
		
		private int? _sourceroleid;
		public virtual int? SourceRoleId
		{
			get
			{
				return this._sourceroleid;
			}
			set
			{
				this._sourceroleid = value;
			}
		}
		
		private int? _destroleid;
		public virtual int? DestRoleId
		{
			get
			{
				return this._destroleid;
			}
			set
			{
				this._destroleid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private short? _enable;
		public virtual short? Enable
		{
			get
			{
				return this._enable;
			}
			set
			{
				this._enable = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
		private Role _role1;
		public virtual Role Role1
		{
			get
			{
				return this._role1;
			}
			set
			{
				this._role1 = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class RoleToRole
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int _rrid;
		public virtual int RrId
		{
			get
			{
				return this._rrid;
			}
			set
			{
				this._rrid = value;
			}
		}
		
		private int? _parentroleid;
		public virtual int? ParentRoleId
		{
			get
			{
				return this._parentroleid;
			}
			set
			{
				this._parentroleid = value;
			}
		}
		
		private int? _childroleid;
		public virtual int? ChildRoleId
		{
			get
			{
				return this._childroleid;
			}
			set
			{
				this._childroleid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
		private Role _role1;
		public virtual Role Role1
		{
			get
			{
				return this._role1;
			}
			set
			{
				this._role1 = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class RoleToGroup
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int? _groupid;
		public virtual int? GroupId
		{
			get
			{
				return this._groupid;
			}
			set
			{
				this._groupid = value;
			}
		}
		
		private int? _roleid;
		public virtual int? RoleId
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private int _rgid;
		public virtual int RgId
		{
			get
			{
				return this._rgid;
			}
			set
			{
				this._rgid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private SecurityGroup _securitygroup;
		public virtual SecurityGroup Securitygroup
		{
			get
			{
				return this._securitygroup;
			}
			set
			{
				this._securitygroup = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class Role
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _rolename;
		public virtual string RoleName
		{
			get
			{
				return this._rolename;
			}
			set
			{
				this._rolename = value;
			}
		}
		
		private int _roleid;
		public virtual int RoleId
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private int? _parentroleid;
		public virtual int? ParentRoleId
		{
			get
			{
				return this._parentroleid;
			}
			set
			{
				this._parentroleid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private string _condidaterolename;
		public virtual string CondidateRoleName
		{
			get
			{
				return this._condidaterolename;
			}
			set
			{
				this._condidaterolename = value;
			}
		}
		
		private int? _appdomainid;
		public virtual int? AppDomainId
		{
			get
			{
				return this._appdomainid;
			}
			set
			{
				this._appdomainid = value;
			}
		}
		
		private IList<UserToRoleConstraint> _usertoroleconstraints = new List<UserToRoleConstraint>();
		public virtual IList<UserToRoleConstraint> UserToRoleConstraints
		{
			get
			{
				return this._usertoroleconstraints;
			}
		}
		
		private IList<UserToRole> _usertoroles = new List<UserToRole>();
		public virtual IList<UserToRole> UserToRoles
		{
			get
			{
				return this._usertoroles;
			}
		}
		
		private IList<RoleToRoleConstraint> _roletoroleconstraints = new List<RoleToRoleConstraint>();
		public virtual IList<RoleToRoleConstraint> RoleToRoleConstraints
		{
			get
			{
				return this._roletoroleconstraints;
			}
		}
		
		private IList<RoleToRoleConstraint> _roletoroleconstraints1 = new List<RoleToRoleConstraint>();
		public virtual IList<RoleToRoleConstraint> RoleToRoleConstraints1
		{
			get
			{
				return this._roletoroleconstraints1;
			}
		}
		
		private IList<RoleToRole> _roletoroles = new List<RoleToRole>();
		public virtual IList<RoleToRole> RoleToRoles
		{
			get
			{
				return this._roletoroles;
			}
		}
		
		private IList<RoleToRole> _roletoroles1 = new List<RoleToRole>();
		public virtual IList<RoleToRole> RoleToRoles1
		{
			get
			{
				return this._roletoroles1;
			}
		}
		
		private IList<RoleToGroup> _roletogroups = new List<RoleToGroup>();
		public virtual IList<RoleToGroup> RoleToGroups
		{
			get
			{
				return this._roletogroups;
			}
		}
		
		private IList<PermissionToRole> _permissiontoroles = new List<PermissionToRole>();
		public virtual IList<PermissionToRole> PermissionToRoles
		{
			get
			{
				return this._permissiontoroles;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class ResourceType
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int _resourcetypeid;
		public virtual int ResourceTypeId
		{
			get
			{
				return this._resourcetypeid;
			}
			set
			{
				this._resourcetypeid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private IList<SecurityResource> _securityresources = new List<SecurityResource>();
		public virtual IList<SecurityResource> SecurityResources
		{
			get
			{
				return this._securityresources;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class ResourceToOperation
	{
		private long? _resourceid;
		public virtual long? ResourceId
		{
			get
			{
				return this._resourceid;
			}
			set
			{
				this._resourceid = value;
			}
		}
		
		private long _resourcetooperationid;
		public virtual long ResourceToOperationId
		{
			get
			{
				return this._resourcetooperationid;
			}
			set
			{
				this._resourcetooperationid = value;
			}
		}
		
		private long? _operationid;
		public virtual long? OperationId
		{
			get
			{
				return this._operationid;
			}
			set
			{
				this._operationid = value;
			}
		}
		
		private Operation _operation;
		public virtual Operation Operation
		{
			get
			{
				return this._operation;
			}
			set
			{
				this._operation = value;
			}
		}
		
		private SecurityResource _securityresource;
		public virtual SecurityResource Securityresource
		{
			get
			{
				return this._securityresource;
			}
			set
			{
				this._securityresource = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class PermissionToUser
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long _userid;
		public virtual long UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private long _permissiontouserid;
		public virtual long PermissionToUserId
		{
			get
			{
				return this._permissiontouserid;
			}
			set
			{
				this._permissiontouserid = value;
			}
		}
		
		private short? _permissionaccess;
		public virtual short? PermissionAccess
		{
			get
			{
				return this._permissionaccess;
			}
			set
			{
				this._permissionaccess = value;
			}
		}
		
		private long _permissionid;
		public virtual long PermissionId
		{
			get
			{
				return this._permissionid;
			}
			set
			{
				this._permissionid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private Permission _permission;
		public virtual Permission Permission
		{
			get
			{
				return this._permission;
			}
			set
			{
				this._permission = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class PermissionToRole
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int _roleid;
		public virtual int RoleId
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private short? _permisssionaccess;
		public virtual short? PermisssionAccess
		{
			get
			{
				return this._permisssionaccess;
			}
			set
			{
				this._permisssionaccess = value;
			}
		}
		
		private long _permissiontoroleid;
		public virtual long PermissionToRoleId
		{
			get
			{
				return this._permissiontoroleid;
			}
			set
			{
				this._permissiontoroleid = value;
			}
		}
		
		private long _permissionid;
		public virtual long PermissionId
		{
			get
			{
				return this._permissionid;
			}
			set
			{
				this._permissionid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private Permission _permission;
		public virtual Permission Permission
		{
			get
			{
				return this._permission;
			}
			set
			{
				this._permission = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class Permission
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long _resourceid;
		public virtual long ResourceId
		{
			get
			{
				return this._resourceid;
			}
			set
			{
				this._resourceid = value;
			}
		}
		
		private long _permissionid;
		public virtual long PermissionId
		{
			get
			{
				return this._permissionid;
			}
			set
			{
				this._permissionid = value;
			}
		}
		
		private long _operationid;
		public virtual long OperationId
		{
			get
			{
				return this._operationid;
			}
			set
			{
				this._operationid = value;
			}
		}
		
		private short? _isdefault;
		public virtual short? IsDefault
		{
			get
			{
				return this._isdefault;
			}
			set
			{
				this._isdefault = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _comments;
		public virtual string Comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments = value;
			}
		}
		
		private Operation _operation;
		public virtual Operation Operation
		{
			get
			{
				return this._operation;
			}
			set
			{
				this._operation = value;
			}
		}
		
		private SecurityResource _securityresource;
		public virtual SecurityResource Securityresource
		{
			get
			{
				return this._securityresource;
			}
			set
			{
				this._securityresource = value;
			}
		}
		
		private IList<PermissionToUser> _permissiontousers = new List<PermissionToUser>();
		public virtual IList<PermissionToUser> PermissionToUsers
		{
			get
			{
				return this._permissiontousers;
			}
		}
		
		private IList<PermissionToRole> _permissiontoroles = new List<PermissionToRole>();
		public virtual IList<PermissionToRole> PermissionToRoles
		{
			get
			{
				return this._permissiontoroles;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class PasswordHistory
	{
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private long _passwordhistoryid;
		public virtual long PasswordHistoryId
		{
			get
			{
				return this._passwordhistoryid;
			}
			set
			{
				this._passwordhistoryid = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private DateTime? _changedate;
		public virtual DateTime? ChangeDate
		{
			get
			{
				return this._changedate;
			}
			set
			{
				this._changedate = value;
			}
		}
		
		private long? _accountid;
		public virtual long? AccountId
		{
			get
			{
				return this._accountid;
			}
			set
			{
				this._accountid = value;
			}
		}
		
		private Account _account;
		public virtual Account Account
		{
			get
			{
				return this._account;
			}
			set
			{
				this._account = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class OperationConstraint
	{
		private long _operationconstraintid;
		public virtual long OperationConstraintId
		{
			get
			{
				return this._operationconstraintid;
			}
			set
			{
				this._operationconstraintid = value;
			}
		}
		
		private long? _srcoperationid;
		public virtual long? SrcOperationId
		{
			get
			{
				return this._srcoperationid;
			}
			set
			{
				this._srcoperationid = value;
			}
		}
		
		private long? _destoperationid;
		public virtual long? DestOperationId
		{
			get
			{
				return this._destoperationid;
			}
			set
			{
				this._destoperationid = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private Operation _operation;
		public virtual Operation Operation
		{
			get
			{
				return this._operation;
			}
			set
			{
				this._operation = value;
			}
		}
		
		private Operation _operation1;
		public virtual Operation Operation1
		{
			get
			{
				return this._operation1;
			}
			set
			{
				this._operation1 = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class Operation
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _operationname;
		public virtual string OperationName
		{
			get
			{
				return this._operationname;
			}
			set
			{
				this._operationname = value;
			}
		}
		
		private long _operationid;
		public virtual long OperationId
		{
			get
			{
				return this._operationid;
			}
			set
			{
				this._operationid = value;
			}
		}
		
		private short? _isdefault;
		public virtual short? IsDefault
		{
			get
			{
				return this._isdefault;
			}
			set
			{
				this._isdefault = value;
			}
		}
		
		private short? _isactionid;
		public virtual short? IsActionId
		{
			get
			{
				return this._isactionid;
			}
			set
			{
				this._isactionid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _displayname;
		public virtual string DisplayName
		{
			get
			{
				return this._displayname;
			}
			set
			{
				this._displayname = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private IList<UserLog> _userlogs = new List<UserLog>();
		public virtual IList<UserLog> UserLogs
		{
			get
			{
				return this._userlogs;
			}
		}
		
		private IList<ResourceToOperation> _resourcetooperations = new List<ResourceToOperation>();
		public virtual IList<ResourceToOperation> ResourceToOperations
		{
			get
			{
				return this._resourcetooperations;
			}
		}
		
		private IList<Permission> _permissions = new List<Permission>();
		public virtual IList<Permission> Permissions
		{
			get
			{
				return this._permissions;
			}
		}
		
		private IList<OperationConstraint> _operationconstraints = new List<OperationConstraint>();
		public virtual IList<OperationConstraint> OperationConstraints
		{
			get
			{
				return this._operationconstraints;
			}
		}
		
		private IList<OperationConstraint> _operationconstraints1 = new List<OperationConstraint>();
		public virtual IList<OperationConstraint> OperationConstraints1
		{
			get
			{
				return this._operationconstraints1;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class ManagementRole
	{
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int _managementroleid;
		public virtual int ManagementRoleId
		{
			get
			{
				return this._managementroleid;
			}
			set
			{
				this._managementroleid = value;
			}
		}
		
		private short? _isactive;
		public virtual short? IsActive
		{
			get
			{
				return this._isactive;
			}
			set
			{
				this._isactive = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private IList<ManagementAccount> _managementaccounts = new List<ManagementAccount>();
		public virtual IList<ManagementAccount> ManagementAccounts
		{
			get
			{
				return this._managementaccounts;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class ManagementLog
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private short? _statues;
		public virtual short? Statues
		{
			get
			{
				return this._statues;
			}
			set
			{
				this._statues = value;
			}
		}
		
		private string _service;
		public virtual string Service
		{
			get
			{
				return this._service;
			}
			set
			{
				this._service = value;
			}
		}
		
		private long? _userid;
		public virtual long? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private string _message;
		public virtual string Message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		
		private long _managementlogid;
		public virtual long ManagementLogId
		{
			get
			{
				return this._managementlogid;
			}
			set
			{
				this._managementlogid = value;
			}
		}
		
		private short? _logtype;
		public virtual short? LogType
		{
			get
			{
				return this._logtype;
			}
			set
			{
				this._logtype = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class ManagementAccount
	{
		private string _username;
		public virtual string UserName
		{
			get
			{
				return this._username;
			}
			set
			{
				this._username = value;
			}
		}
		
		private long _securityuserid;
		public virtual long SecurityUserId
		{
			get
			{
				return this._securityuserid;
			}
			set
			{
				this._securityuserid = value;
			}
		}
		
		private string _personelcode;
		public virtual string PersonelCode
		{
			get
			{
				return this._personelcode;
			}
			set
			{
				this._personelcode = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private int? _managementroleid;
		public virtual int? ManagementRoleId
		{
			get
			{
				return this._managementroleid;
			}
			set
			{
				this._managementroleid = value;
			}
		}
		
		private int _managementaccountid;
		public virtual int ManagementAccountId
		{
			get
			{
				return this._managementaccountid;
			}
			set
			{
				this._managementaccountid = value;
			}
		}
		
		private DateTime? _expiredate;
		public virtual DateTime? ExpireDate
		{
			get
			{
				return this._expiredate;
			}
			set
			{
				this._expiredate = value;
			}
		}
		
		private ManagementRole _managementrole;
		public virtual ManagementRole Managementrole
		{
			get
			{
				return this._managementrole;
			}
			set
			{
				this._managementrole = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class LoginType
	{
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private short _logintypeid;
		public virtual short LoginTypeId
		{
			get
			{
				return this._logintypeid;
			}
			set
			{
				this._logintypeid = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private IList<ApplicationDomain> _applicationdomains = new List<ApplicationDomain>();
		public virtual IList<ApplicationDomain> ApplicationDomains
		{
			get
			{
				return this._applicationdomains;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class GroupToGroup
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int? _parentgroupid;
		public virtual int? ParentGroupId
		{
			get
			{
				return this._parentgroupid;
			}
			set
			{
				this._parentgroupid = value;
			}
		}
		
		private int? _childgroupid;
		public virtual int? ChildGroupId
		{
			get
			{
				return this._childgroupid;
			}
			set
			{
				this._childgroupid = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private int _ggid;
		public virtual int GgId
		{
			get
			{
				return this._ggid;
			}
			set
			{
				this._ggid = value;
			}
		}
		
		private SecurityGroup _securitygroup;
		public virtual SecurityGroup Securitygroup
		{
			get
			{
				return this._securitygroup;
			}
			set
			{
				this._securitygroup = value;
			}
		}
		
		private SecurityGroup _securitygroup1;
		public virtual SecurityGroup Securitygroup1
		{
			get
			{
				return this._securitygroup1;
			}
			set
			{
				this._securitygroup1 = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class Company
	{
		private int _companyid;
		public virtual int CompanyId
		{
			get
			{
				return this._companyid;
			}
			set
			{
				this._companyid = value;
			}
		}
		
		private string _nationalno;
		public virtual string NationalNo
		{
			get
			{
				return this._nationalno;
			}
			set
			{
				this._nationalno = value;
			}
		}
		
		private short _haspersonel;
		public virtual short HasPersonel
		{
			get
			{
				return this._haspersonel;
			}
			set
			{
				this._haspersonel = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _registerno;
		public virtual string RegisterNo
		{
			get
			{
				return this._registerno;
			}
			set
			{
				this._registerno = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class ApplicationDomain
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private short? _logintypeid;
		public virtual short? LoginTypeId
		{
			get
			{
				return this._logintypeid;
			}
			set
			{
				this._logintypeid = value;
			}
		}
		
		private short? _locked;
		public virtual short? Locked
		{
			get
			{
				return this._locked;
			}
			set
			{
				this._locked = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private int _applicationdomainid;
		public virtual int ApplicationDomainId
		{
			get
			{
				return this._applicationdomainid;
			}
			set
			{
				this._applicationdomainid = value;
			}
		}
		
		private LoginType _logintype;
		public virtual LoginType Logintype
		{
			get
			{
				return this._logintype;
			}
			set
			{
				this._logintype = value;
			}
		}
		
		private IList<SecurityResource> _securityresources = new List<SecurityResource>();
		public virtual IList<SecurityResource> SecurityResources
		{
			get
			{
				return this._securityresources;
			}
		}
		
		private IList<AccountToAppDomain> _accounttoappdomains = new List<AccountToAppDomain>();
		public virtual IList<AccountToAppDomain> AccountToAppDomains
		{
			get
			{
				return this._accounttoappdomains;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class AccountToAppDomain
	{
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private DateTime? _expiredate;
		public virtual DateTime? ExpireDate
		{
			get
			{
				return this._expiredate;
			}
			set
			{
				this._expiredate = value;
			}
		}
		
		private int _appdomainid;
		public virtual int AppDomainId
		{
			get
			{
				return this._appdomainid;
			}
			set
			{
				this._appdomainid = value;
			}
		}
		
		private long _accountid;
		public virtual long AccountId
		{
			get
			{
				return this._accountid;
			}
			set
			{
				this._accountid = value;
			}
		}
		
		private long _accaapdomainid;
		public virtual long AccAapdomainId
		{
			get
			{
				return this._accaapdomainid;
			}
			set
			{
				this._accaapdomainid = value;
			}
		}
		
		private Account _account;
		public virtual Account Account
		{
			get
			{
				return this._account;
			}
			set
			{
				this._account = value;
			}
		}
		
		private ApplicationDomain _applicationdomain;
		public virtual ApplicationDomain Applicationdomain
		{
			get
			{
				return this._applicationdomain;
			}
			set
			{
				this._applicationdomain = value;
			}
		}
		
	}
}
namespace ISE.SM.Model	
{
	public partial class Account
	{
		private string _username;
		public virtual string Username
		{
			get
			{
				return this._username;
			}
			set
			{
				this._username = value;
			}
		}
		
		private int? _updateperid;
		public virtual int? UpdatePerId
		{
			get
			{
				return this._updateperid;
			}
			set
			{
				this._updateperid = value;
			}
		}
		
		private DateTime? _updatedate;
		public virtual DateTime? UpdateDate
		{
			get
			{
				return this._updatedate;
			}
			set
			{
				this._updatedate = value;
			}
		}
		
		private long _userid;
		public virtual long UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _passchangedatefa;
		public virtual string PassChangeDateFa
		{
			get
			{
				return this._passchangedatefa;
			}
			set
			{
				this._passchangedatefa = value;
			}
		}
		
		private int? _insertperid;
		public virtual int? InsertPerId
		{
			get
			{
				return this._insertperid;
			}
			set
			{
				this._insertperid = value;
			}
		}
		
		private DateTime? _insertdate;
		public virtual DateTime? InsertDate
		{
			get
			{
				return this._insertdate;
			}
			set
			{
				this._insertdate = value;
			}
		}
		
		private string _expireddatefa;
		public virtual string ExpiredDateFa
		{
			get
			{
				return this._expireddatefa;
			}
			set
			{
				this._expireddatefa = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private long _accountid;
		public virtual long AccountId
		{
			get
			{
				return this._accountid;
			}
			set
			{
				this._accountid = value;
			}
		}
		
		private string _createdatefa;
		public virtual string CreateDateFa
		{
			get
			{
				return this._createdatefa;
			}
			set
			{
				this._createdatefa = value;
			}
		}
		
		private DateTime? _passchangedate;
		public virtual DateTime? PassChangeDate
		{
			get
			{
				return this._passchangedate;
			}
			set
			{
				this._passchangedate = value;
			}
		}
		
		private DateTime? _expireddate;
		public virtual DateTime? ExpiredDate
		{
			get
			{
				return this._expireddate;
			}
			set
			{
				this._expireddate = value;
			}
		}
		
		private DateTime? _createdate;
		public virtual DateTime? CreateDate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				this._createdate = value;
			}
		}
		
		private short? _locked;
		public virtual short? Locked
		{
			get
			{
				return this._locked;
			}
			set
			{
				this._locked = value;
			}
		}
		
		private short? _isactivedirectory;
		public virtual short? IsActiveDirectory
		{
			get
			{
				return this._isactivedirectory;
			}
			set
			{
				this._isactivedirectory = value;
			}
		}
		
		private User _user;
		public virtual User User
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
		private IList<SecurityUserLog> _securityuserlogs = new List<SecurityUserLog>();
		public virtual IList<SecurityUserLog> SecurityUserLogs
		{
			get
			{
				return this._securityuserlogs;
			}
		}
		
		private IList<SecuritySession> _securitysessions = new List<SecuritySession>();
		public virtual IList<SecuritySession> SecuritySessions
		{
			get
			{
				return this._securitysessions;
			}
		}
		
		private IList<PasswordHistory> _passwordhistories = new List<PasswordHistory>();
		public virtual IList<PasswordHistory> PasswordHistories
		{
			get
			{
				return this._passwordhistories;
			}
		}
		
		private IList<AccountToAppDomain> _accounttoappdomains = new List<AccountToAppDomain>();
		public virtual IList<AccountToAppDomain> AccountToAppDomains
		{
			get
			{
				return this._accounttoappdomains;
			}
		}
		
	}
}
#pragma warning restore 1591
