#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

using System.Runtime.Serialization;

	#region Dto Class
	
namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserDto")]
	public partial class UserDto
	{
		private int? _updateuserid;
		[DataMember(Name = "UpdateUserId", IsRequired = false)]
		public virtual int? UpdateUserId 
		{ 
		    get
		    {
		        return this._updateuserid;
		    }
		    set
		    {
		        this._updateuserid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _personelcode;
		[DataMember(Name = "PersonelCode", IsRequired = false)]
		public virtual string PersonelCode 
		{ 
		    get
		    {
		        return this._personelcode;
		    }
		    set
		    {
		        this._personelcode = value;
		    }
		}
		
		private int? _perid;
		[DataMember(Name = "PerId", IsRequired = false)]
		public virtual int? PerId 
		{ 
		    get
		    {
		        return this._perid;
		    }
		    set
		    {
		        this._perid = value;
		    }
		}
		
		private string _nationalno;
		[DataMember(Name = "NationalNo", IsRequired = false)]
		public virtual string NationalNo 
		{ 
		    get
		    {
		        return this._nationalno;
		    }
		    set
		    {
		        this._nationalno = value;
		    }
		}
		
		private string _lastname;
		[DataMember(Name = "LastName", IsRequired = false)]
		public virtual string LastName 
		{ 
		    get
		    {
		        return this._lastname;
		    }
		    set
		    {
		        this._lastname = value;
		    }
		}
		
		private short? _isrealperson;
		[DataMember(Name = "IsRealPerson", IsRequired = false)]
		public virtual short? IsRealPerson 
		{ 
		    get
		    {
		        return this._isrealperson;
		    }
		    set
		    {
		        this._isrealperson = value;
		    }
		}
		
		private int? _insertuserid;
		[DataMember(Name = "InsertUserId", IsRequired = false)]
		public virtual int? InsertUserId 
		{ 
		    get
		    {
		        return this._insertuserid;
		    }
		    set
		    {
		        this._insertuserid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _firstname;
		[DataMember(Name = "FirstName", IsRequired = false)]
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this._firstname;
		    }
		    set
		    {
		        this._firstname = value;
		    }
		}
		
		private DateTime? _lockdate;
		[DataMember(Name = "LockDate", IsRequired = false)]
		public virtual DateTime? LockDate 
		{ 
		    get
		    {
		        return this._lockdate;
		    }
		    set
		    {
		        this._lockdate = value;
		    }
		}
		
		private int? _companyid;
		[DataMember(Name = "CompanyId", IsRequired = false)]
		public virtual int? CompanyId 
		{ 
		    get
		    {
		        return this._companyid;
		    }
		    set
		    {
		        this._companyid = value;
		    }
		}
		
		private int _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual int UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private IList<AccountDto> _accounts = new List<AccountDto>();
		[DataMember(Name = "Accounts", IsRequired = false)]
		public virtual IList<AccountDto> Accounts 
		{ 
		    get
		    {
		        return this._accounts;
		    }
		    set
		    {
		        this._accounts = value;
		    }
		}
		
		private IList<UserLogDto> _userlogs = new List<UserLogDto>();
		[DataMember(Name = "UserLogs", IsRequired = false)]
		public virtual IList<UserLogDto> UserLogs 
		{ 
		    get
		    {
		        return this._userlogs;
		    }
		    set
		    {
		        this._userlogs = value;
		    }
		}
		
		private IList<UserProfileDto> _userprofiles = new List<UserProfileDto>();
		[DataMember(Name = "UserProfiles", IsRequired = false)]
		public virtual IList<UserProfileDto> UserProfiles 
		{ 
		    get
		    {
		        return this._userprofiles;
		    }
		    set
		    {
		        this._userprofiles = value;
		    }
		}
		
		private IList<UserResourceScopeDto> _userresourcescopes = new List<UserResourceScopeDto>();
		[DataMember(Name = "UserResourceScopes", IsRequired = false)]
		public virtual IList<UserResourceScopeDto> UserResourceScopes 
		{ 
		    get
		    {
		        return this._userresourcescopes;
		    }
		    set
		    {
		        this._userresourcescopes = value;
		    }
		}
		
		private IList<UserToCompanyDto> _usertocompanies = new List<UserToCompanyDto>();
		[DataMember(Name = "UserToCompanies", IsRequired = false)]
		public virtual IList<UserToCompanyDto> UserToCompanies 
		{ 
		    get
		    {
		        return this._usertocompanies;
		    }
		    set
		    {
		        this._usertocompanies = value;
		    }
		}
		
		private IList<UserToGroupDto> _usertogroups = new List<UserToGroupDto>();
		[DataMember(Name = "UserToGroups", IsRequired = false)]
		public virtual IList<UserToGroupDto> UserToGroups 
		{ 
		    get
		    {
		        return this._usertogroups;
		    }
		    set
		    {
		        this._usertogroups = value;
		    }
		}
		
		private IList<UserToRoleDto> _usertoroles = new List<UserToRoleDto>();
		[DataMember(Name = "UserToRoles", IsRequired = false)]
		public virtual IList<UserToRoleDto> UserToRoles 
		{ 
		    get
		    {
		        return this._usertoroles;
		    }
		    set
		    {
		        this._usertoroles = value;
		    }
		}
		
		private IList<UserToRoleConstraintDto> _usertoroleconstraints = new List<UserToRoleConstraintDto>();
		[DataMember(Name = "UserToRoleConstraints", IsRequired = false)]
		public virtual IList<UserToRoleConstraintDto> UserToRoleConstraints 
		{ 
		    get
		    {
		        return this._usertoroleconstraints;
		    }
		    set
		    {
		        this._usertoroleconstraints = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserToRoleConstraintDto")]
	public partial class UserToRoleConstraintDto
	{
		private long _urconstraintid;
		[DataMember(Name = "UrConstraintId", IsRequired = false)]
		public virtual long UrConstraintId 
		{ 
		    get
		    {
		        return this._urconstraintid;
		    }
		    set
		    {
		        this._urconstraintid = value;
		    }
		}
		
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private int? _roleid;
		[DataMember(Name = "RoleId", IsRequired = false)]
		public virtual int? RoleId 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private short? _enable;
		[DataMember(Name = "Enable", IsRequired = false)]
		public virtual short? Enable 
		{ 
		    get
		    {
		        return this._enable;
		    }
		    set
		    {
		        this._enable = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserToRoleDto")]
	public partial class UserToRoleDto
	{
		private long _urid;
		[DataMember(Name = "UrId", IsRequired = false)]
		public virtual long UrId 
		{ 
		    get
		    {
		        return this._urid;
		    }
		    set
		    {
		        this._urid = value;
		    }
		}
		
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private int? _roleid;
		[DataMember(Name = "RoleId", IsRequired = false)]
		public virtual int? RoleId 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserToGroupDto")]
	public partial class UserToGroupDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int _ugid;
		[DataMember(Name = "UgId", IsRequired = false)]
		public virtual int UgId 
		{ 
		    get
		    {
		        return this._ugid;
		    }
		    set
		    {
		        this._ugid = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private int? _groupid;
		[DataMember(Name = "GroupId", IsRequired = false)]
		public virtual int? GroupId 
		{ 
		    get
		    {
		        return this._groupid;
		    }
		    set
		    {
		        this._groupid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserToCompanyDto")]
	public partial class UserToCompanyDto
	{
		private long _usertocompanyid;
		[DataMember(Name = "UserToCompanyId", IsRequired = false)]
		public virtual long UserToCompanyId 
		{ 
		    get
		    {
		        return this._usertocompanyid;
		    }
		    set
		    {
		        this._usertocompanyid = value;
		    }
		}
		
		private DateTime? _todate;
		[DataMember(Name = "ToDate", IsRequired = false)]
		public virtual DateTime? ToDate 
		{ 
		    get
		    {
		        return this._todate;
		    }
		    set
		    {
		        this._todate = value;
		    }
		}
		
		private long? _securityuserid;
		[DataMember(Name = "SecurityUserId", IsRequired = false)]
		public virtual long? SecurityUserId 
		{ 
		    get
		    {
		        return this._securityuserid;
		    }
		    set
		    {
		        this._securityuserid = value;
		    }
		}
		
		private int? _companyid;
		[DataMember(Name = "CompanyId", IsRequired = false)]
		public virtual int? CompanyId 
		{ 
		    get
		    {
		        return this._companyid;
		    }
		    set
		    {
		        this._companyid = value;
		    }
		}
		
		private DateTime? _fromdate;
		[DataMember(Name = "FromDate", IsRequired = false)]
		public virtual DateTime? FromDate 
		{ 
		    get
		    {
		        return this._fromdate;
		    }
		    set
		    {
		        this._fromdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserResourceScopeDto")]
	public partial class UserResourceScopeDto
	{
		private long _userresourcescopeid;
		[DataMember(Name = "UserResourceScopeId", IsRequired = false)]
		public virtual long UserResourceScopeId 
		{ 
		    get
		    {
		        return this._userresourcescopeid;
		    }
		    set
		    {
		        this._userresourcescopeid = value;
		    }
		}
		
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private long? _resourceid;
		[DataMember(Name = "ResourceId", IsRequired = false)]
		public virtual long? ResourceId 
		{ 
		    get
		    {
		        return this._resourceid;
		    }
		    set
		    {
		        this._resourceid = value;
		    }
		}
		
		private int? _scopeid;
		[DataMember(Name = "ScopeId", IsRequired = false)]
		public virtual int? ScopeId 
		{ 
		    get
		    {
		        return this._scopeid;
		    }
		    set
		    {
		        this._scopeid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserProfileDto")]
	public partial class UserProfileDto
	{
		private long _userprofileid;
		[DataMember(Name = "UserProfileId", IsRequired = false)]
		public virtual long UserProfileId 
		{ 
		    get
		    {
		        return this._userprofileid;
		    }
		    set
		    {
		        this._userprofileid = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "UserLogDto")]
	public partial class UserLogDto
	{
		private long _userlogid;
		[DataMember(Name = "UserLogId", IsRequired = false)]
		public virtual long UserLogId 
		{ 
		    get
		    {
		        return this._userlogid;
		    }
		    set
		    {
		        this._userlogid = value;
		    }
		}
		
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private long? _resourceid;
		[DataMember(Name = "ResourceId", IsRequired = false)]
		public virtual long? ResourceId 
		{ 
		    get
		    {
		        return this._resourceid;
		    }
		    set
		    {
		        this._resourceid = value;
		    }
		}
		
		private short? _runtype;
		[DataMember(Name = "RunType", IsRequired = false)]
		public virtual short? RunType 
		{ 
		    get
		    {
		        return this._runtype;
		    }
		    set
		    {
		        this._runtype = value;
		    }
		}
		
		private long? _operationid;
		[DataMember(Name = "OperationId", IsRequired = false)]
		public virtual long? OperationId 
		{ 
		    get
		    {
		        return this._operationid;
		    }
		    set
		    {
		        this._operationid = value;
		    }
		}
		
		private DateTime? _logdatetime;
		[DataMember(Name = "LogDateTime", IsRequired = false)]
		public virtual DateTime? LogDateTime 
		{ 
		    get
		    {
		        return this._logdatetime;
		    }
		    set
		    {
		        this._logdatetime = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _computername;
		[DataMember(Name = "ComputerName", IsRequired = false)]
		public virtual string ComputerName 
		{ 
		    get
		    {
		        return this._computername;
		    }
		    set
		    {
		        this._computername = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "SoftwareDomainDto")]
	public partial class SoftwareDomainDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private int _softwaredomainid;
		[DataMember(Name = "SoftwareDomainId", IsRequired = false)]
		public virtual int SoftwareDomainId 
		{ 
		    get
		    {
		        return this._softwaredomainid;
		    }
		    set
		    {
		        this._softwaredomainid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private int? _precedency;
		[DataMember(Name = "Precedency", IsRequired = false)]
		public virtual int? Precedency 
		{ 
		    get
		    {
		        return this._precedency;
		    }
		    set
		    {
		        this._precedency = value;
		    }
		}
		
		private IList<SecurityResourceDto> _securityresources = new List<SecurityResourceDto>();
		[DataMember(Name = "SecurityResources", IsRequired = false)]
		public virtual IList<SecurityResourceDto> SecurityResources 
		{ 
		    get
		    {
		        return this._securityresources;
		    }
		    set
		    {
		        this._securityresources = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "SecurityUserLogDto")]
	public partial class SecurityUserLogDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _service;
		[DataMember(Name = "Service", IsRequired = false)]
		public virtual string Service 
		{ 
		    get
		    {
		        return this._service;
		    }
		    set
		    {
		        this._service = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private string _sessionid;
		[DataMember(Name = "SessionId", IsRequired = false)]
		public virtual string SessionId 
		{ 
		    get
		    {
		        return this._sessionid;
		    }
		    set
		    {
		        this._sessionid = value;
		    }
		}
		
		private long _securityuserlogid;
		[DataMember(Name = "SecurityUserLogId", IsRequired = false)]
		public virtual long SecurityUserLogId 
		{ 
		    get
		    {
		        return this._securityuserlogid;
		    }
		    set
		    {
		        this._securityuserlogid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private int? _appdomainid;
		[DataMember(Name = "AppDomainId", IsRequired = false)]
		public virtual int? AppDomainId 
		{ 
		    get
		    {
		        return this._appdomainid;
		    }
		    set
		    {
		        this._appdomainid = value;
		    }
		}
		
		private string _actionparam;
		[DataMember(Name = "ActionParam", IsRequired = false)]
		public virtual string ActionParam 
		{ 
		    get
		    {
		        return this._actionparam;
		    }
		    set
		    {
		        this._actionparam = value;
		    }
		}
		
		private string _action;
		[DataMember(Name = "Action", IsRequired = false)]
		public virtual string Action 
		{ 
		    get
		    {
		        return this._action;
		    }
		    set
		    {
		        this._action = value;
		    }
		}
		
		private long? _accountid;
		[DataMember(Name = "AccountId", IsRequired = false)]
		public virtual long? AccountId 
		{ 
		    get
		    {
		        return this._accountid;
		    }
		    set
		    {
		        this._accountid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "SecuritySessionDto")]
	public partial class SecuritySessionDto
	{
		private string _securitysessionid;
		[DataMember(Name = "SecuritySessionId", IsRequired = false)]
		public virtual string SecuritySessionId 
		{ 
		    get
		    {
		        return this._securitysessionid;
		    }
		    set
		    {
		        this._securitysessionid = value;
		    }
		}
		
		private DateTime? _expireddate;
		[DataMember(Name = "ExpiredDate", IsRequired = false)]
		public virtual DateTime? ExpiredDate 
		{ 
		    get
		    {
		        return this._expireddate;
		    }
		    set
		    {
		        this._expireddate = value;
		    }
		}
		
		private DateTime? _createdate;
		[DataMember(Name = "CreateDate", IsRequired = false)]
		public virtual DateTime? CreateDate 
		{ 
		    get
		    {
		        return this._createdate;
		    }
		    set
		    {
		        this._createdate = value;
		    }
		}
		
		private int? _appdomainid;
		[DataMember(Name = "AppDomainId", IsRequired = false)]
		public virtual int? AppDomainId 
		{ 
		    get
		    {
		        return this._appdomainid;
		    }
		    set
		    {
		        this._appdomainid = value;
		    }
		}
		
		private long? _accountid;
		[DataMember(Name = "AccountId", IsRequired = false)]
		public virtual long? AccountId 
		{ 
		    get
		    {
		        return this._accountid;
		    }
		    set
		    {
		        this._accountid = value;
		    }
		}
		
		private long _rowid;
		[DataMember(Name = "RowId", IsRequired = false)]
		public virtual long RowId 
		{ 
		    get
		    {
		        return this._rowid;
		    }
		    set
		    {
		        this._rowid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "SecurityResourceDto")]
	public partial class SecurityResourceDto
	{
		private string _userdescription;
		[DataMember(Name = "UserDescription", IsRequired = false)]
		public virtual string UserDescription 
		{ 
		    get
		    {
		        return this._userdescription;
		    }
		    set
		    {
		        this._userdescription = value;
		    }
		}
		
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _tooltip;
		[DataMember(Name = "ToolTip", IsRequired = false)]
		public virtual string ToolTip 
		{ 
		    get
		    {
		        return this._tooltip;
		    }
		    set
		    {
		        this._tooltip = value;
		    }
		}
		
		private string _systempassword;
		[DataMember(Name = "SystemPassword", IsRequired = false)]
		public virtual string SystemPassword 
		{ 
		    get
		    {
		        return this._systempassword;
		    }
		    set
		    {
		        this._systempassword = value;
		    }
		}
		
		private int? _softwaredomainid;
		[DataMember(Name = "SoftwareDomainId", IsRequired = false)]
		public virtual int? SoftwareDomainId 
		{ 
		    get
		    {
		        return this._softwaredomainid;
		    }
		    set
		    {
		        this._softwaredomainid = value;
		    }
		}
		
		private long _securityresourceid;
		[DataMember(Name = "SecurityResourceId", IsRequired = false)]
		public virtual long SecurityResourceId 
		{ 
		    get
		    {
		        return this._securityresourceid;
		    }
		    set
		    {
		        this._securityresourceid = value;
		    }
		}
		
		private int? _resourcetypeid;
		[DataMember(Name = "ResourceTypeId", IsRequired = false)]
		public virtual int? ResourceTypeId 
		{ 
		    get
		    {
		        return this._resourcetypeid;
		    }
		    set
		    {
		        this._resourcetypeid = value;
		    }
		}
		
		private string _resourcename;
		[DataMember(Name = "ResourceName", IsRequired = false)]
		public virtual string ResourceName 
		{ 
		    get
		    {
		        return this._resourcename;
		    }
		    set
		    {
		        this._resourcename = value;
		    }
		}
		
		private int? _precedence;
		[DataMember(Name = "Precedence", IsRequired = false)]
		public virtual int? Precedence 
		{ 
		    get
		    {
		        return this._precedence;
		    }
		    set
		    {
		        this._precedence = value;
		    }
		}
		
		private string _path;
		[DataMember(Name = "Path", IsRequired = false)]
		public virtual string Path 
		{ 
		    get
		    {
		        return this._path;
		    }
		    set
		    {
		        this._path = value;
		    }
		}
		
		private long? _parentid;
		[DataMember(Name = "ParentId", IsRequired = false)]
		public virtual long? ParentId 
		{ 
		    get
		    {
		        return this._parentid;
		    }
		    set
		    {
		        this._parentid = value;
		    }
		}
		
		private string _namespace;
		[DataMember(Name = "Namespace", IsRequired = false)]
		public virtual string Namespace 
		{ 
		    get
		    {
		        return this._namespace;
		    }
		    set
		    {
		        this._namespace = value;
		    }
		}
		
		private string _loginname;
		[DataMember(Name = "LoginName", IsRequired = false)]
		public virtual string LoginName 
		{ 
		    get
		    {
		        return this._loginname;
		    }
		    set
		    {
		        this._loginname = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _icon;
		[DataMember(Name = "Icon", IsRequired = false)]
		public virtual string Icon 
		{ 
		    get
		    {
		        return this._icon;
		    }
		    set
		    {
		        this._icon = value;
		    }
		}
		
		private short? _hasparameter;
		[DataMember(Name = "HasParameter", IsRequired = false)]
		public virtual short? HasParameter 
		{ 
		    get
		    {
		        return this._hasparameter;
		    }
		    set
		    {
		        this._hasparameter = value;
		    }
		}
		
		private short? _hasitemaction;
		[DataMember(Name = "HasItemAction", IsRequired = false)]
		public virtual short? HasItemAction 
		{ 
		    get
		    {
		        return this._hasitemaction;
		    }
		    set
		    {
		        this._hasitemaction = value;
		    }
		}
		
		private string _executablefile;
		[DataMember(Name = "ExecutableFile", IsRequired = false)]
		public virtual string ExecutableFile 
		{ 
		    get
		    {
		        return this._executablefile;
		    }
		    set
		    {
		        this._executablefile = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private string _displayname;
		[DataMember(Name = "DisplayName", IsRequired = false)]
		public virtual string DisplayName 
		{ 
		    get
		    {
		        return this._displayname;
		    }
		    set
		    {
		        this._displayname = value;
		    }
		}
		
		private string _devdescription;
		[DataMember(Name = "DevDescription", IsRequired = false)]
		public virtual string DevDescription 
		{ 
		    get
		    {
		        return this._devdescription;
		    }
		    set
		    {
		        this._devdescription = value;
		    }
		}
		
		private string _call3;
		[DataMember(Name = "Call3", IsRequired = false)]
		public virtual string Call3 
		{ 
		    get
		    {
		        return this._call3;
		    }
		    set
		    {
		        this._call3 = value;
		    }
		}
		
		private string _call2;
		[DataMember(Name = "Call2", IsRequired = false)]
		public virtual string Call2 
		{ 
		    get
		    {
		        return this._call2;
		    }
		    set
		    {
		        this._call2 = value;
		    }
		}
		
		private string _call1;
		[DataMember(Name = "Call1", IsRequired = false)]
		public virtual string Call1 
		{ 
		    get
		    {
		        return this._call1;
		    }
		    set
		    {
		        this._call1 = value;
		    }
		}
		
		private string _assemblyname;
		[DataMember(Name = "AssemblyName", IsRequired = false)]
		public virtual string AssemblyName 
		{ 
		    get
		    {
		        return this._assemblyname;
		    }
		    set
		    {
		        this._assemblyname = value;
		    }
		}
		
		private int? _appdomainid;
		[DataMember(Name = "AppDomainId", IsRequired = false)]
		public virtual int? AppDomainId 
		{ 
		    get
		    {
		        return this._appdomainid;
		    }
		    set
		    {
		        this._appdomainid = value;
		    }
		}
		
		private IList<UserResourceScopeDto> _userresourcescopes = new List<UserResourceScopeDto>();
		[DataMember(Name = "UserResourceScopes", IsRequired = false)]
		public virtual IList<UserResourceScopeDto> UserResourceScopes 
		{ 
		    get
		    {
		        return this._userresourcescopes;
		    }
		    set
		    {
		        this._userresourcescopes = value;
		    }
		}
		
		private IList<UserLogDto> _userlogs = new List<UserLogDto>();
		[DataMember(Name = "UserLogs", IsRequired = false)]
		public virtual IList<UserLogDto> UserLogs 
		{ 
		    get
		    {
		        return this._userlogs;
		    }
		    set
		    {
		        this._userlogs = value;
		    }
		}
		
		private IList<ResourceToOperationDto> _resourcetooperations = new List<ResourceToOperationDto>();
		[DataMember(Name = "ResourceToOperations", IsRequired = false)]
		public virtual IList<ResourceToOperationDto> ResourceToOperations 
		{ 
		    get
		    {
		        return this._resourcetooperations;
		    }
		    set
		    {
		        this._resourcetooperations = value;
		    }
		}
		
		private IList<PermissionDto> _permissions = new List<PermissionDto>();
		[DataMember(Name = "Permissions", IsRequired = false)]
		public virtual IList<PermissionDto> Permissions 
		{ 
		    get
		    {
		        return this._permissions;
		    }
		    set
		    {
		        this._permissions = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "SecurityGroupDto")]
	public partial class SecurityGroupDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int _securitygroupid;
		[DataMember(Name = "SecurityGroupId", IsRequired = false)]
		public virtual int SecurityGroupId 
		{ 
		    get
		    {
		        return this._securitygroupid;
		    }
		    set
		    {
		        this._securitygroupid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _groupname;
		[DataMember(Name = "GroupName", IsRequired = false)]
		public virtual string GroupName 
		{ 
		    get
		    {
		        return this._groupname;
		    }
		    set
		    {
		        this._groupname = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private string _displayname;
		[DataMember(Name = "DisplayName", IsRequired = false)]
		public virtual string DisplayName 
		{ 
		    get
		    {
		        return this._displayname;
		    }
		    set
		    {
		        this._displayname = value;
		    }
		}
		
		private int? _appdomainid;
		[DataMember(Name = "AppDomainId", IsRequired = false)]
		public virtual int? AppDomainId 
		{ 
		    get
		    {
		        return this._appdomainid;
		    }
		    set
		    {
		        this._appdomainid = value;
		    }
		}
		
		private IList<UserToGroupDto> _usertogroups = new List<UserToGroupDto>();
		[DataMember(Name = "UserToGroups", IsRequired = false)]
		public virtual IList<UserToGroupDto> UserToGroups 
		{ 
		    get
		    {
		        return this._usertogroups;
		    }
		    set
		    {
		        this._usertogroups = value;
		    }
		}
		
		private IList<RoleToGroupDto> _roletogroups = new List<RoleToGroupDto>();
		[DataMember(Name = "RoleToGroups", IsRequired = false)]
		public virtual IList<RoleToGroupDto> RoleToGroups 
		{ 
		    get
		    {
		        return this._roletogroups;
		    }
		    set
		    {
		        this._roletogroups = value;
		    }
		}
		
		private IList<GroupToGroupDto> _grouptogroups = new List<GroupToGroupDto>();
		[DataMember(Name = "GroupToGroups", IsRequired = false)]
		public virtual IList<GroupToGroupDto> GroupToGroups 
		{ 
		    get
		    {
		        return this._grouptogroups;
		    }
		    set
		    {
		        this._grouptogroups = value;
		    }
		}
		
		private IList<GroupToGroupDto> _grouptogroups1 = new List<GroupToGroupDto>();
		[DataMember(Name = "GroupToGroups1", IsRequired = false)]
		public virtual IList<GroupToGroupDto> GroupToGroups1 
		{ 
		    get
		    {
		        return this._grouptogroups1;
		    }
		    set
		    {
		        this._grouptogroups1 = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ScopeDto")]
	public partial class ScopeDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _scopename;
		[DataMember(Name = "ScopeName", IsRequired = false)]
		public virtual string ScopeName 
		{ 
		    get
		    {
		        return this._scopename;
		    }
		    set
		    {
		        this._scopename = value;
		    }
		}
		
		private int _scopeid;
		[DataMember(Name = "ScopeId", IsRequired = false)]
		public virtual int ScopeId 
		{ 
		    get
		    {
		        return this._scopeid;
		    }
		    set
		    {
		        this._scopeid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _displayname;
		[DataMember(Name = "DisplayName", IsRequired = false)]
		public virtual string DisplayName 
		{ 
		    get
		    {
		        return this._displayname;
		    }
		    set
		    {
		        this._displayname = value;
		    }
		}
		
		private IList<UserResourceScopeDto> _userresourcescopes = new List<UserResourceScopeDto>();
		[DataMember(Name = "UserResourceScopes", IsRequired = false)]
		public virtual IList<UserResourceScopeDto> UserResourceScopes 
		{ 
		    get
		    {
		        return this._userresourcescopes;
		    }
		    set
		    {
		        this._userresourcescopes = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "RoleToRoleConstraintDto")]
	public partial class RoleToRoleConstraintDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int _rrconstraintid;
		[DataMember(Name = "RrConstraintId", IsRequired = false)]
		public virtual int RrConstraintId 
		{ 
		    get
		    {
		        return this._rrconstraintid;
		    }
		    set
		    {
		        this._rrconstraintid = value;
		    }
		}
		
		private int? _sourceroleid;
		[DataMember(Name = "SourceRoleId", IsRequired = false)]
		public virtual int? SourceRoleId 
		{ 
		    get
		    {
		        return this._sourceroleid;
		    }
		    set
		    {
		        this._sourceroleid = value;
		    }
		}
		
		private int? _destroleid;
		[DataMember(Name = "DestRoleId", IsRequired = false)]
		public virtual int? DestRoleId 
		{ 
		    get
		    {
		        return this._destroleid;
		    }
		    set
		    {
		        this._destroleid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private short? _enable;
		[DataMember(Name = "Enable", IsRequired = false)]
		public virtual short? Enable 
		{ 
		    get
		    {
		        return this._enable;
		    }
		    set
		    {
		        this._enable = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "RoleToRoleDto")]
	public partial class RoleToRoleDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int _rrid;
		[DataMember(Name = "RrId", IsRequired = false)]
		public virtual int RrId 
		{ 
		    get
		    {
		        return this._rrid;
		    }
		    set
		    {
		        this._rrid = value;
		    }
		}
		
		private int? _parentroleid;
		[DataMember(Name = "ParentRoleId", IsRequired = false)]
		public virtual int? ParentRoleId 
		{ 
		    get
		    {
		        return this._parentroleid;
		    }
		    set
		    {
		        this._parentroleid = value;
		    }
		}
		
		private int? _childroleid;
		[DataMember(Name = "ChildRoleId", IsRequired = false)]
		public virtual int? ChildRoleId 
		{ 
		    get
		    {
		        return this._childroleid;
		    }
		    set
		    {
		        this._childroleid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "RoleToGroupDto")]
	public partial class RoleToGroupDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int? _groupid;
		[DataMember(Name = "GroupId", IsRequired = false)]
		public virtual int? GroupId 
		{ 
		    get
		    {
		        return this._groupid;
		    }
		    set
		    {
		        this._groupid = value;
		    }
		}
		
		private int? _roleid;
		[DataMember(Name = "RoleId", IsRequired = false)]
		public virtual int? RoleId 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private int _rgid;
		[DataMember(Name = "RgId", IsRequired = false)]
		public virtual int RgId 
		{ 
		    get
		    {
		        return this._rgid;
		    }
		    set
		    {
		        this._rgid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "RoleDto")]
	public partial class RoleDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _rolename;
		[DataMember(Name = "RoleName", IsRequired = false)]
		public virtual string RoleName 
		{ 
		    get
		    {
		        return this._rolename;
		    }
		    set
		    {
		        this._rolename = value;
		    }
		}
		
		private int _roleid;
		[DataMember(Name = "RoleId", IsRequired = false)]
		public virtual int RoleId 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private int? _parentroleid;
		[DataMember(Name = "ParentRoleId", IsRequired = false)]
		public virtual int? ParentRoleId 
		{ 
		    get
		    {
		        return this._parentroleid;
		    }
		    set
		    {
		        this._parentroleid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private string _condidaterolename;
		[DataMember(Name = "CondidateRoleName", IsRequired = false)]
		public virtual string CondidateRoleName 
		{ 
		    get
		    {
		        return this._condidaterolename;
		    }
		    set
		    {
		        this._condidaterolename = value;
		    }
		}
		
		private int? _appdomainid;
		[DataMember(Name = "AppDomainId", IsRequired = false)]
		public virtual int? AppDomainId 
		{ 
		    get
		    {
		        return this._appdomainid;
		    }
		    set
		    {
		        this._appdomainid = value;
		    }
		}
		
		private IList<UserToRoleConstraintDto> _usertoroleconstraints = new List<UserToRoleConstraintDto>();
		[DataMember(Name = "UserToRoleConstraints", IsRequired = false)]
		public virtual IList<UserToRoleConstraintDto> UserToRoleConstraints 
		{ 
		    get
		    {
		        return this._usertoroleconstraints;
		    }
		    set
		    {
		        this._usertoroleconstraints = value;
		    }
		}
		
		private IList<UserToRoleDto> _usertoroles = new List<UserToRoleDto>();
		[DataMember(Name = "UserToRoles", IsRequired = false)]
		public virtual IList<UserToRoleDto> UserToRoles 
		{ 
		    get
		    {
		        return this._usertoroles;
		    }
		    set
		    {
		        this._usertoroles = value;
		    }
		}
		
		private IList<RoleToRoleConstraintDto> _roletoroleconstraints = new List<RoleToRoleConstraintDto>();
		[DataMember(Name = "RoleToRoleConstraints", IsRequired = false)]
		public virtual IList<RoleToRoleConstraintDto> RoleToRoleConstraints 
		{ 
		    get
		    {
		        return this._roletoroleconstraints;
		    }
		    set
		    {
		        this._roletoroleconstraints = value;
		    }
		}
		
		private IList<RoleToRoleConstraintDto> _roletoroleconstraints1 = new List<RoleToRoleConstraintDto>();
		[DataMember(Name = "RoleToRoleConstraints1", IsRequired = false)]
		public virtual IList<RoleToRoleConstraintDto> RoleToRoleConstraints1 
		{ 
		    get
		    {
		        return this._roletoroleconstraints1;
		    }
		    set
		    {
		        this._roletoroleconstraints1 = value;
		    }
		}
		
		private IList<RoleToRoleDto> _roletoroles = new List<RoleToRoleDto>();
		[DataMember(Name = "RoleToRoles", IsRequired = false)]
		public virtual IList<RoleToRoleDto> RoleToRoles 
		{ 
		    get
		    {
		        return this._roletoroles;
		    }
		    set
		    {
		        this._roletoroles = value;
		    }
		}
		
		private IList<RoleToRoleDto> _roletoroles1 = new List<RoleToRoleDto>();
		[DataMember(Name = "RoleToRoles1", IsRequired = false)]
		public virtual IList<RoleToRoleDto> RoleToRoles1 
		{ 
		    get
		    {
		        return this._roletoroles1;
		    }
		    set
		    {
		        this._roletoroles1 = value;
		    }
		}
		
		private IList<RoleToGroupDto> _roletogroups = new List<RoleToGroupDto>();
		[DataMember(Name = "RoleToGroups", IsRequired = false)]
		public virtual IList<RoleToGroupDto> RoleToGroups 
		{ 
		    get
		    {
		        return this._roletogroups;
		    }
		    set
		    {
		        this._roletogroups = value;
		    }
		}
		
		private IList<PermissionToRoleDto> _permissiontoroles = new List<PermissionToRoleDto>();
		[DataMember(Name = "PermissionToRoles", IsRequired = false)]
		public virtual IList<PermissionToRoleDto> PermissionToRoles 
		{ 
		    get
		    {
		        return this._permissiontoroles;
		    }
		    set
		    {
		        this._permissiontoroles = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ResourceTypeDto")]
	public partial class ResourceTypeDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private int _resourcetypeid;
		[DataMember(Name = "ResourceTypeId", IsRequired = false)]
		public virtual int ResourceTypeId 
		{ 
		    get
		    {
		        return this._resourcetypeid;
		    }
		    set
		    {
		        this._resourcetypeid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private IList<SecurityResourceDto> _securityresources = new List<SecurityResourceDto>();
		[DataMember(Name = "SecurityResources", IsRequired = false)]
		public virtual IList<SecurityResourceDto> SecurityResources 
		{ 
		    get
		    {
		        return this._securityresources;
		    }
		    set
		    {
		        this._securityresources = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ResourceToOperationDto")]
	public partial class ResourceToOperationDto
	{
		private long? _resourceid;
		[DataMember(Name = "ResourceId", IsRequired = false)]
		public virtual long? ResourceId 
		{ 
		    get
		    {
		        return this._resourceid;
		    }
		    set
		    {
		        this._resourceid = value;
		    }
		}
		
		private long _resourcetooperationid;
		[DataMember(Name = "ResourceToOperationId", IsRequired = false)]
		public virtual long ResourceToOperationId 
		{ 
		    get
		    {
		        return this._resourcetooperationid;
		    }
		    set
		    {
		        this._resourcetooperationid = value;
		    }
		}
		
		private long? _operationid;
		[DataMember(Name = "OperationId", IsRequired = false)]
		public virtual long? OperationId 
		{ 
		    get
		    {
		        return this._operationid;
		    }
		    set
		    {
		        this._operationid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "PermissionToUserDto")]
	public partial class PermissionToUserDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private long _permissiontouserid;
		[DataMember(Name = "PermissionToUserId", IsRequired = false)]
		public virtual long PermissionToUserId 
		{ 
		    get
		    {
		        return this._permissiontouserid;
		    }
		    set
		    {
		        this._permissiontouserid = value;
		    }
		}
		
		private short? _permissionaccess;
		[DataMember(Name = "PermissionAccess", IsRequired = false)]
		public virtual short? PermissionAccess 
		{ 
		    get
		    {
		        return this._permissionaccess;
		    }
		    set
		    {
		        this._permissionaccess = value;
		    }
		}
		
		private long _permissionid;
		[DataMember(Name = "PermissionId", IsRequired = false)]
		public virtual long PermissionId 
		{ 
		    get
		    {
		        return this._permissionid;
		    }
		    set
		    {
		        this._permissionid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "PermissionToRoleDto")]
	public partial class PermissionToRoleDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int _roleid;
		[DataMember(Name = "RoleId", IsRequired = false)]
		public virtual int RoleId 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private short? _permisssionaccess;
		[DataMember(Name = "PermisssionAccess", IsRequired = false)]
		public virtual short? PermisssionAccess 
		{ 
		    get
		    {
		        return this._permisssionaccess;
		    }
		    set
		    {
		        this._permisssionaccess = value;
		    }
		}
		
		private long _permissiontoroleid;
		[DataMember(Name = "PermissionToRoleId", IsRequired = false)]
		public virtual long PermissionToRoleId 
		{ 
		    get
		    {
		        return this._permissiontoroleid;
		    }
		    set
		    {
		        this._permissiontoroleid = value;
		    }
		}
		
		private long _permissionid;
		[DataMember(Name = "PermissionId", IsRequired = false)]
		public virtual long PermissionId 
		{ 
		    get
		    {
		        return this._permissionid;
		    }
		    set
		    {
		        this._permissionid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "PermissionDto")]
	public partial class PermissionDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long _resourceid;
		[DataMember(Name = "ResourceId", IsRequired = false)]
		public virtual long ResourceId 
		{ 
		    get
		    {
		        return this._resourceid;
		    }
		    set
		    {
		        this._resourceid = value;
		    }
		}
		
		private long _permissionid;
		[DataMember(Name = "PermissionId", IsRequired = false)]
		public virtual long PermissionId 
		{ 
		    get
		    {
		        return this._permissionid;
		    }
		    set
		    {
		        this._permissionid = value;
		    }
		}
		
		private long _operationid;
		[DataMember(Name = "OperationId", IsRequired = false)]
		public virtual long OperationId 
		{ 
		    get
		    {
		        return this._operationid;
		    }
		    set
		    {
		        this._operationid = value;
		    }
		}
		
		private short? _isdefault;
		[DataMember(Name = "IsDefault", IsRequired = false)]
		public virtual short? IsDefault 
		{ 
		    get
		    {
		        return this._isdefault;
		    }
		    set
		    {
		        this._isdefault = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _comments;
		[DataMember(Name = "Comments", IsRequired = false)]
		public virtual string Comments 
		{ 
		    get
		    {
		        return this._comments;
		    }
		    set
		    {
		        this._comments = value;
		    }
		}
		
		private IList<PermissionToUserDto> _permissiontousers = new List<PermissionToUserDto>();
		[DataMember(Name = "PermissionToUsers", IsRequired = false)]
		public virtual IList<PermissionToUserDto> PermissionToUsers 
		{ 
		    get
		    {
		        return this._permissiontousers;
		    }
		    set
		    {
		        this._permissiontousers = value;
		    }
		}
		
		private IList<PermissionToRoleDto> _permissiontoroles = new List<PermissionToRoleDto>();
		[DataMember(Name = "PermissionToRoles", IsRequired = false)]
		public virtual IList<PermissionToRoleDto> PermissionToRoles 
		{ 
		    get
		    {
		        return this._permissiontoroles;
		    }
		    set
		    {
		        this._permissiontoroles = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "PasswordHistoryDto")]
	public partial class PasswordHistoryDto
	{
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private long _passwordhistoryid;
		[DataMember(Name = "PasswordHistoryId", IsRequired = false)]
		public virtual long PasswordHistoryId 
		{ 
		    get
		    {
		        return this._passwordhistoryid;
		    }
		    set
		    {
		        this._passwordhistoryid = value;
		    }
		}
		
		private string _password;
		[DataMember(Name = "Password", IsRequired = false)]
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
		private DateTime? _changedate;
		[DataMember(Name = "ChangeDate", IsRequired = false)]
		public virtual DateTime? ChangeDate 
		{ 
		    get
		    {
		        return this._changedate;
		    }
		    set
		    {
		        this._changedate = value;
		    }
		}
		
		private long? _accountid;
		[DataMember(Name = "AccountId", IsRequired = false)]
		public virtual long? AccountId 
		{ 
		    get
		    {
		        return this._accountid;
		    }
		    set
		    {
		        this._accountid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "OperationConstraintDto")]
	public partial class OperationConstraintDto
	{
		private long _operationconstraintid;
		[DataMember(Name = "OperationConstraintId", IsRequired = false)]
		public virtual long OperationConstraintId 
		{ 
		    get
		    {
		        return this._operationconstraintid;
		    }
		    set
		    {
		        this._operationconstraintid = value;
		    }
		}
		
		private long? _srcoperationid;
		[DataMember(Name = "SrcOperationId", IsRequired = false)]
		public virtual long? SrcOperationId 
		{ 
		    get
		    {
		        return this._srcoperationid;
		    }
		    set
		    {
		        this._srcoperationid = value;
		    }
		}
		
		private long? _destoperationid;
		[DataMember(Name = "DestOperationId", IsRequired = false)]
		public virtual long? DestOperationId 
		{ 
		    get
		    {
		        return this._destoperationid;
		    }
		    set
		    {
		        this._destoperationid = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "OperationDto")]
	public partial class OperationDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _operationname;
		[DataMember(Name = "OperationName", IsRequired = false)]
		public virtual string OperationName 
		{ 
		    get
		    {
		        return this._operationname;
		    }
		    set
		    {
		        this._operationname = value;
		    }
		}
		
		private long _operationid;
		[DataMember(Name = "OperationId", IsRequired = false)]
		public virtual long OperationId 
		{ 
		    get
		    {
		        return this._operationid;
		    }
		    set
		    {
		        this._operationid = value;
		    }
		}
		
		private short? _isdefault;
		[DataMember(Name = "IsDefault", IsRequired = false)]
		public virtual short? IsDefault 
		{ 
		    get
		    {
		        return this._isdefault;
		    }
		    set
		    {
		        this._isdefault = value;
		    }
		}
		
		private short? _isactionid;
		[DataMember(Name = "IsActionId", IsRequired = false)]
		public virtual short? IsActionId 
		{ 
		    get
		    {
		        return this._isactionid;
		    }
		    set
		    {
		        this._isactionid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _displayname;
		[DataMember(Name = "DisplayName", IsRequired = false)]
		public virtual string DisplayName 
		{ 
		    get
		    {
		        return this._displayname;
		    }
		    set
		    {
		        this._displayname = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private IList<UserLogDto> _userlogs = new List<UserLogDto>();
		[DataMember(Name = "UserLogs", IsRequired = false)]
		public virtual IList<UserLogDto> UserLogs 
		{ 
		    get
		    {
		        return this._userlogs;
		    }
		    set
		    {
		        this._userlogs = value;
		    }
		}
		
		private IList<ResourceToOperationDto> _resourcetooperations = new List<ResourceToOperationDto>();
		[DataMember(Name = "ResourceToOperations", IsRequired = false)]
		public virtual IList<ResourceToOperationDto> ResourceToOperations 
		{ 
		    get
		    {
		        return this._resourcetooperations;
		    }
		    set
		    {
		        this._resourcetooperations = value;
		    }
		}
		
		private IList<PermissionDto> _permissions = new List<PermissionDto>();
		[DataMember(Name = "Permissions", IsRequired = false)]
		public virtual IList<PermissionDto> Permissions 
		{ 
		    get
		    {
		        return this._permissions;
		    }
		    set
		    {
		        this._permissions = value;
		    }
		}
		
		private IList<OperationConstraintDto> _operationconstraints = new List<OperationConstraintDto>();
		[DataMember(Name = "OperationConstraints", IsRequired = false)]
		public virtual IList<OperationConstraintDto> OperationConstraints 
		{ 
		    get
		    {
		        return this._operationconstraints;
		    }
		    set
		    {
		        this._operationconstraints = value;
		    }
		}
		
		private IList<OperationConstraintDto> _operationconstraints1 = new List<OperationConstraintDto>();
		[DataMember(Name = "OperationConstraints1", IsRequired = false)]
		public virtual IList<OperationConstraintDto> OperationConstraints1 
		{ 
		    get
		    {
		        return this._operationconstraints1;
		    }
		    set
		    {
		        this._operationconstraints1 = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ManagementRoleDto")]
	public partial class ManagementRoleDto
	{
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private int _managementroleid;
		[DataMember(Name = "ManagementRoleId", IsRequired = false)]
		public virtual int ManagementRoleId 
		{ 
		    get
		    {
		        return this._managementroleid;
		    }
		    set
		    {
		        this._managementroleid = value;
		    }
		}
		
		private short? _isactive;
		[DataMember(Name = "IsActive", IsRequired = false)]
		public virtual short? IsActive 
		{ 
		    get
		    {
		        return this._isactive;
		    }
		    set
		    {
		        this._isactive = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private IList<ManagementAccountDto> _managementaccounts = new List<ManagementAccountDto>();
		[DataMember(Name = "ManagementAccounts", IsRequired = false)]
		public virtual IList<ManagementAccountDto> ManagementAccounts 
		{ 
		    get
		    {
		        return this._managementaccounts;
		    }
		    set
		    {
		        this._managementaccounts = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ManagementLogDto")]
	public partial class ManagementLogDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private short? _statues;
		[DataMember(Name = "Statues", IsRequired = false)]
		public virtual short? Statues 
		{ 
		    get
		    {
		        return this._statues;
		    }
		    set
		    {
		        this._statues = value;
		    }
		}
		
		private string _service;
		[DataMember(Name = "Service", IsRequired = false)]
		public virtual string Service 
		{ 
		    get
		    {
		        return this._service;
		    }
		    set
		    {
		        this._service = value;
		    }
		}
		
		private long? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private string _message;
		[DataMember(Name = "Message", IsRequired = false)]
		public virtual string Message 
		{ 
		    get
		    {
		        return this._message;
		    }
		    set
		    {
		        this._message = value;
		    }
		}
		
		private long _managementlogid;
		[DataMember(Name = "ManagementLogId", IsRequired = false)]
		public virtual long ManagementLogId 
		{ 
		    get
		    {
		        return this._managementlogid;
		    }
		    set
		    {
		        this._managementlogid = value;
		    }
		}
		
		private short? _logtype;
		[DataMember(Name = "LogType", IsRequired = false)]
		public virtual short? LogType 
		{ 
		    get
		    {
		        return this._logtype;
		    }
		    set
		    {
		        this._logtype = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ManagementAccountDto")]
	public partial class ManagementAccountDto
	{
		private string _username;
		[DataMember(Name = "UserName", IsRequired = false)]
		public virtual string UserName 
		{ 
		    get
		    {
		        return this._username;
		    }
		    set
		    {
		        this._username = value;
		    }
		}
		
		private long _securityuserid;
		[DataMember(Name = "SecurityUserId", IsRequired = false)]
		public virtual long SecurityUserId 
		{ 
		    get
		    {
		        return this._securityuserid;
		    }
		    set
		    {
		        this._securityuserid = value;
		    }
		}
		
		private string _personelcode;
		[DataMember(Name = "PersonelCode", IsRequired = false)]
		public virtual string PersonelCode 
		{ 
		    get
		    {
		        return this._personelcode;
		    }
		    set
		    {
		        this._personelcode = value;
		    }
		}
		
		private string _password;
		[DataMember(Name = "Password", IsRequired = false)]
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
		private int? _managementroleid;
		[DataMember(Name = "ManagementRoleId", IsRequired = false)]
		public virtual int? ManagementRoleId 
		{ 
		    get
		    {
		        return this._managementroleid;
		    }
		    set
		    {
		        this._managementroleid = value;
		    }
		}
		
		private int _managementaccountid;
		[DataMember(Name = "ManagementAccountId", IsRequired = false)]
		public virtual int ManagementAccountId 
		{ 
		    get
		    {
		        return this._managementaccountid;
		    }
		    set
		    {
		        this._managementaccountid = value;
		    }
		}
		
		private DateTime? _expiredate;
		[DataMember(Name = "ExpireDate", IsRequired = false)]
		public virtual DateTime? ExpireDate 
		{ 
		    get
		    {
		        return this._expiredate;
		    }
		    set
		    {
		        this._expiredate = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "LoginTypeDto")]
	public partial class LoginTypeDto
	{
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private short _logintypeid;
		[DataMember(Name = "LoginTypeId", IsRequired = false)]
		public virtual short LoginTypeId 
		{ 
		    get
		    {
		        return this._logintypeid;
		    }
		    set
		    {
		        this._logintypeid = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private IList<ApplicationDomainDto> _applicationdomains = new List<ApplicationDomainDto>();
		[DataMember(Name = "ApplicationDomains", IsRequired = false)]
		public virtual IList<ApplicationDomainDto> ApplicationDomains 
		{ 
		    get
		    {
		        return this._applicationdomains;
		    }
		    set
		    {
		        this._applicationdomains = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "GroupToGroupDto")]
	public partial class GroupToGroupDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int? _parentgroupid;
		[DataMember(Name = "ParentGroupId", IsRequired = false)]
		public virtual int? ParentGroupId 
		{ 
		    get
		    {
		        return this._parentgroupid;
		    }
		    set
		    {
		        this._parentgroupid = value;
		    }
		}
		
		private int? _childgroupid;
		[DataMember(Name = "ChildGroupId", IsRequired = false)]
		public virtual int? ChildGroupId 
		{ 
		    get
		    {
		        return this._childgroupid;
		    }
		    set
		    {
		        this._childgroupid = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private int _ggid;
		[DataMember(Name = "GgId", IsRequired = false)]
		public virtual int GgId 
		{ 
		    get
		    {
		        return this._ggid;
		    }
		    set
		    {
		        this._ggid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "CompanyDto")]
	public partial class CompanyDto
	{
		private int _companyid;
		[DataMember(Name = "CompanyId", IsRequired = false)]
		public virtual int CompanyId 
		{ 
		    get
		    {
		        return this._companyid;
		    }
		    set
		    {
		        this._companyid = value;
		    }
		}
		
		private string _nationalno;
		[DataMember(Name = "NationalNo", IsRequired = false)]
		public virtual string NationalNo 
		{ 
		    get
		    {
		        return this._nationalno;
		    }
		    set
		    {
		        this._nationalno = value;
		    }
		}
		
		private short _haspersonel;
		[DataMember(Name = "HasPersonel", IsRequired = false)]
		public virtual short HasPersonel 
		{ 
		    get
		    {
		        return this._haspersonel;
		    }
		    set
		    {
		        this._haspersonel = value;
		    }
		}
		
		private string _name;
		[DataMember(Name = "Name", IsRequired = false)]
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _registerno;
		[DataMember(Name = "RegisterNo", IsRequired = false)]
		public virtual string RegisterNo 
		{ 
		    get
		    {
		        return this._registerno;
		    }
		    set
		    {
		        this._registerno = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "ApplicationDomainDto")]
	public partial class ApplicationDomainDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private short? _logintypeid;
		[DataMember(Name = "LoginTypeId", IsRequired = false)]
		public virtual short? LoginTypeId 
		{ 
		    get
		    {
		        return this._logintypeid;
		    }
		    set
		    {
		        this._logintypeid = value;
		    }
		}
		
		private short? _locked;
		[DataMember(Name = "Locked", IsRequired = false)]
		public virtual short? Locked 
		{ 
		    get
		    {
		        return this._locked;
		    }
		    set
		    {
		        this._locked = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private int _applicationdomainid;
		[DataMember(Name = "ApplicationDomainId", IsRequired = false)]
		public virtual int ApplicationDomainId 
		{ 
		    get
		    {
		        return this._applicationdomainid;
		    }
		    set
		    {
		        this._applicationdomainid = value;
		    }
		}
		
		private IList<SecurityResourceDto> _securityresources = new List<SecurityResourceDto>();
		[DataMember(Name = "SecurityResources", IsRequired = false)]
		public virtual IList<SecurityResourceDto> SecurityResources 
		{ 
		    get
		    {
		        return this._securityresources;
		    }
		    set
		    {
		        this._securityresources = value;
		    }
		}
		
		private IList<AccountToAppDomainDto> _accounttoappdomains = new List<AccountToAppDomainDto>();
		[DataMember(Name = "AccountToAppDomains", IsRequired = false)]
		public virtual IList<AccountToAppDomainDto> AccountToAppDomains 
		{ 
		    get
		    {
		        return this._accounttoappdomains;
		    }
		    set
		    {
		        this._accounttoappdomains = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "AccountToAppDomainDto")]
	public partial class AccountToAppDomainDto
	{
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private DateTime? _expiredate;
		[DataMember(Name = "ExpireDate", IsRequired = false)]
		public virtual DateTime? ExpireDate 
		{ 
		    get
		    {
		        return this._expiredate;
		    }
		    set
		    {
		        this._expiredate = value;
		    }
		}
		
		private int _appdomainid;
		[DataMember(Name = "AppDomainId", IsRequired = false)]
		public virtual int AppDomainId 
		{ 
		    get
		    {
		        return this._appdomainid;
		    }
		    set
		    {
		        this._appdomainid = value;
		    }
		}
		
		private long _accountid;
		[DataMember(Name = "AccountId", IsRequired = false)]
		public virtual long AccountId 
		{ 
		    get
		    {
		        return this._accountid;
		    }
		    set
		    {
		        this._accountid = value;
		    }
		}
		
		private long _accaapdomainid;
		[DataMember(Name = "AccAapdomainId", IsRequired = false)]
		public virtual long AccAapdomainId 
		{ 
		    get
		    {
		        return this._accaapdomainid;
		    }
		    set
		    {
		        this._accaapdomainid = value;
		    }
		}
		
	}
}

namespace ISE.SM.Common.DTO	
{
	[DataContract(Name = "AccountDto")]
	public partial class AccountDto
	{
		private string _username;
		[DataMember(Name = "Username", IsRequired = false)]
		public virtual string Username 
		{ 
		    get
		    {
		        return this._username;
		    }
		    set
		    {
		        this._username = value;
		    }
		}
		
		private int? _updateperid;
		[DataMember(Name = "UpdatePerId", IsRequired = false)]
		public virtual int? UpdatePerId 
		{ 
		    get
		    {
		        return this._updateperid;
		    }
		    set
		    {
		        this._updateperid = value;
		    }
		}
		
		private DateTime? _updatedate;
		[DataMember(Name = "UpdateDate", IsRequired = false)]
		public virtual DateTime? UpdateDate 
		{ 
		    get
		    {
		        return this._updatedate;
		    }
		    set
		    {
		        this._updatedate = value;
		    }
		}
		
		private long _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual long UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private string _password;
		[DataMember(Name = "Password", IsRequired = false)]
		public virtual string Password 
		{ 
		    get
		    {
		        return this._password;
		    }
		    set
		    {
		        this._password = value;
		    }
		}
		
		private string _passchangedatefa;
		[DataMember(Name = "PassChangeDateFa", IsRequired = false)]
		public virtual string PassChangeDateFa 
		{ 
		    get
		    {
		        return this._passchangedatefa;
		    }
		    set
		    {
		        this._passchangedatefa = value;
		    }
		}
		
		private int? _insertperid;
		[DataMember(Name = "InsertPerId", IsRequired = false)]
		public virtual int? InsertPerId 
		{ 
		    get
		    {
		        return this._insertperid;
		    }
		    set
		    {
		        this._insertperid = value;
		    }
		}
		
		private DateTime? _insertdate;
		[DataMember(Name = "InsertDate", IsRequired = false)]
		public virtual DateTime? InsertDate 
		{ 
		    get
		    {
		        return this._insertdate;
		    }
		    set
		    {
		        this._insertdate = value;
		    }
		}
		
		private string _expireddatefa;
		[DataMember(Name = "ExpiredDateFa", IsRequired = false)]
		public virtual string ExpiredDateFa 
		{ 
		    get
		    {
		        return this._expireddatefa;
		    }
		    set
		    {
		        this._expireddatefa = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private long _accountid;
		[DataMember(Name = "AccountId", IsRequired = false)]
		public virtual long AccountId 
		{ 
		    get
		    {
		        return this._accountid;
		    }
		    set
		    {
		        this._accountid = value;
		    }
		}
		
		private string _createdatefa;
		[DataMember(Name = "CreateDateFa", IsRequired = false)]
		public virtual string CreateDateFa 
		{ 
		    get
		    {
		        return this._createdatefa;
		    }
		    set
		    {
		        this._createdatefa = value;
		    }
		}
		
		private DateTime? _passchangedate;
		[DataMember(Name = "PassChangeDate", IsRequired = false)]
		public virtual DateTime? PassChangeDate 
		{ 
		    get
		    {
		        return this._passchangedate;
		    }
		    set
		    {
		        this._passchangedate = value;
		    }
		}
		
		private DateTime? _expireddate;
		[DataMember(Name = "ExpiredDate", IsRequired = false)]
		public virtual DateTime? ExpiredDate 
		{ 
		    get
		    {
		        return this._expireddate;
		    }
		    set
		    {
		        this._expireddate = value;
		    }
		}
		
		private DateTime? _createdate;
		[DataMember(Name = "CreateDate", IsRequired = false)]
		public virtual DateTime? CreateDate 
		{ 
		    get
		    {
		        return this._createdate;
		    }
		    set
		    {
		        this._createdate = value;
		    }
		}
		
		private short? _locked;
		[DataMember(Name = "Locked", IsRequired = false)]
		public virtual short? Locked 
		{ 
		    get
		    {
		        return this._locked;
		    }
		    set
		    {
		        this._locked = value;
		    }
		}
		
		private short? _isactivedirectory;
		[DataMember(Name = "IsActiveDirectory", IsRequired = false)]
		public virtual short? IsActiveDirectory 
		{ 
		    get
		    {
		        return this._isactivedirectory;
		    }
		    set
		    {
		        this._isactivedirectory = value;
		    }
		}
		
		private IList<SecurityUserLogDto> _securityuserlogs = new List<SecurityUserLogDto>();
		[DataMember(Name = "SecurityUserLogs", IsRequired = false)]
		public virtual IList<SecurityUserLogDto> SecurityUserLogs 
		{ 
		    get
		    {
		        return this._securityuserlogs;
		    }
		    set
		    {
		        this._securityuserlogs = value;
		    }
		}
		
		private IList<SecuritySessionDto> _securitysessions = new List<SecuritySessionDto>();
		[DataMember(Name = "SecuritySessions", IsRequired = false)]
		public virtual IList<SecuritySessionDto> SecuritySessions 
		{ 
		    get
		    {
		        return this._securitysessions;
		    }
		    set
		    {
		        this._securitysessions = value;
		    }
		}
		
		private IList<PasswordHistoryDto> _passwordhistories = new List<PasswordHistoryDto>();
		[DataMember(Name = "PasswordHistories", IsRequired = false)]
		public virtual IList<PasswordHistoryDto> PasswordHistories 
		{ 
		    get
		    {
		        return this._passwordhistories;
		    }
		    set
		    {
		        this._passwordhistories = value;
		    }
		}
		
		private IList<AccountToAppDomainDto> _accounttoappdomains = new List<AccountToAppDomainDto>();
		[DataMember(Name = "AccountToAppDomains", IsRequired = false)]
		public virtual IList<AccountToAppDomainDto> AccountToAppDomains 
		{ 
		    get
		    {
		        return this._accounttoappdomains;
		    }
		    set
		    {
		        this._accounttoappdomains = value;
		    }
		}
		
	}
}
	#endregion
	#pragma warning restore 1591
